// Unit tests for the TEACHER ANSWER KEY sheet (T8).
//
// The key moved from an inline per-problem note (T4) to dedicated A4 pages
// appended after the worksheet pages. These tests pin:
//   1. the rendered content (id + answer rows, key title, page footer);
//   2. the CAPACITY MODEL — a maximally full key page (KEY_PER_PAGE rows)
//      fits the printable A4 height with a large margin, and the longest
//      answer string generated by ANY spec/grade fits one key row (this is
//      the size-assumption evidence the T8 brief demands);
//   3. the chunking contract used by worksheet-kit (buildPageSpecs).
import { describe, it, expect } from 'vitest';
import React from 'react';
import { render } from '@testing-library/react';
import { seedFrom, getGradeConfig, createRng } from '../framework';
import { AnswerKeySheet, KEY_PER_PAGE, KEY_ROWS_PER_PAGE, KEY_COLS } from './AnswerKeySheet';
import * as PINS from '../plugins/pins';

// ── Chrome constants mirroring AnswerKeySheet.tsx (px at 96dpi, 1mm = 96/25.4)
const MM = 96 / 25.4;
const A4_W = 794, A4_H = 1123;
const PAD = 12 * MM;                              // KeyRoot padding 12mm
const HEADER = 30 * 1.1 + 4 + 15 * 1.2 + 14;      // title + mb + subtitle + KeyHeader mb
const RULE = 2 + 16;                              // KeyRule border + margin-bottom
const FOOTER = 14 + 11 * 1.2;                     // KeyFooter paddingTop + line
const KEY_ROW_H = 30;                             // KeyGrid gridAutoRows / KeyRow height
const KEY_FONT = 18;                              // KeyRow fontSize
const INDEX_W = 26, ROW_GAP_X = 10;               // KeyIndex minWidth + KeyRow gap
const EM = 0.55;                                  // conservative glyph advance (layout-capacity model)

describe('AnswerKeySheet — rendered content', () => {
    it('prints the key title, the owning worksheet title, and id + answer rows', () => {
        const { container } = render(
            <AnswerKeySheet
                title="Year 4 — Decimals"
                entries={[{ id: 1, answer: '0.6' }, { id: 12, answer: 'thousandths' }]}
                pageLabel="Page 2 of 2"
            />
        );
        const t = container.textContent ?? '';
        // Index and answer are adjacent spans (JSX strips whitespace), so the
        // row textContent is exactly "1.0.6" / "12.thousandths".
        expect(t).toContain('Answer key');
        expect(t).toContain('Year 4 — Decimals');
        expect(t).toContain('1.0.6');
        expect(t).toContain('12.thousandths');
        expect(t).toContain('Page 2 of 2');
    });

    it('omits the footer when no pageLabel is given (single-page documents)', () => {
        const { container } = render(<AnswerKeySheet title="Prep — Counting" entries={[{ id: 1, answer: '4' }]} />);
        expect(container.textContent).not.toContain('Page');
    });
});

describe('AnswerKeySheet — capacity model (T8 size assumptions)', () => {
    it('a FULL key page (KEY_PER_PAGE rows) fits the printable height with margin', () => {
        // ONE column × KEY_ROWS_PER_PAGE fixed 30px rows + header/rule/footer.
        expect(KEY_COLS).toBe(1);
        expect(KEY_ROWS_PER_PAGE).toBe(25);
        expect(KEY_PER_PAGE).toBe(25);
        const content = KEY_ROWS_PER_PAGE * KEY_ROW_H; // 750px of answer rows
        const used = HEADER + RULE + content + FOOTER;
        const printable = A4_H - 2 * PAD;              // ~1032px inside the padding
        expect(used).toBeLessThanOrEqual(printable - 150); // ≥150px safety margin
    });

    it('the longest answer ANY spec generates fits one key row (width model)', () => {
        // Sweep every spec × offered grade at the layout-capacity ask (1000)
        // and take the single longest answer string in the whole catalogue
        // (the clock word answer "12:00 — hour hand on 12, minute hand on 12"
        // is the known worst case — the reason the key is single-column).
        let longest = '';
        for (const spec of Object.values(PINS)) {
            for (const gradeId of [0, 1, 2, 3, 4, 5, 6]) {
                const grade = getGradeConfig(gradeId);
                if (!grade.implemented || !spec.offered(grade)) continue;
                const problems = spec.generate(createRng(seedFrom([grade.id, spec.id, 0])), grade.caps, 1000);
                for (const p of problems) if (p.answer.length > longest.length) longest = p.answer;
            }
        }
        // Single-column text width for a key row (index gutter removed).
        const textW = A4_W - 2 * PAD - INDEX_W - ROW_GAP_X;
        const worstPx = longest.length * KEY_FONT * EM;
        expect(worstPx, `longest answer "${longest}"`).toBeLessThanOrEqual(textW);
    });
});
