// ─────────────────────────────────────────────────────────────────────────────
// ADDITION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `AdditionWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Addition", glyph "+") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Addition worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Addition within opCap. a is never the full cap and b >= 1 whenever possible,
// so we avoid the trivial "x + 0" and guarantee a + b <= opCap.
function generateAddition(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const aMax = Math.max(1, caps.opCap - 1);
    for (let i = 0; i < count; i++) {
        const a = rng.int(1, aMax);
        const bMax = caps.opCap - a; // >= 1 because a <= opCap-1
        const b = bMax >= 1 ? rng.int(1, bMax) : 0;
        out.push({ prompt: `${a} + ${b} = __`, answer: `${a + b}` });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const additionSpec: WorksheetSpec = {
    id: 'addition',
    label: 'Addition',
    icon: '+',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('addition'),
    scope: (grade: GradeConfig) => `within ${grade.caps.opCap}`,
    generate: generateAddition
};

// The plugin: a function the dashboard calls with its framework bundle.
export function AdditionWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(additionSpec);
}
