// ─────────────────────────────────────────────────────────────────────────────
// CLOCK FACES WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `ClockWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Clock Faces', glyph '⏱') and which grades offer it
//     (only grades whose catalogue lists 'clock' AND whose clockCap > 0 —
//     currently Year 2 only);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// VISUAL SHEET: unlike the text-only worksheets, every item here carries an
// optional `clock` figure (framework/types.ts ClockFigure). The framework's
// sheet renderer (PrintableSheet) draws a small SVG analog clock before the
// prompt — hands drawn for READING items, a BLANK face for DRAWING items the
// student completes by hand.
//
// Exercise kinds (mixed on every sheet):
//   read-words        clock with hands  → write the WORD form ("half past 3")
//   read-digital      clock with hands  → write the DIGITAL form ("3:30")
//   draw              blank clock face  → draw the hands for a word form
//   words-to-digital  "Half past 10 is the same time in digital:" (line below)
//   digital-to-words  "7:45 is the same time in words:" (answer line below)
//
// Fully self-contained: the clock vocabulary lives IN this plugin (duplicated
// deliberately — plugins never import from each other, not even from
// TimeWorksheet). Deleting this file and its line in plugins/index.ts removes
// the Clock worksheet without affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// The five exercise kinds mixed onto every sheet (see header comment).
const MODES = ['read-words', 'read-digital', 'draw', 'words-to-digital', 'digital-to-words'] as const;

// Minute positions the sheet practices: o'clock, quarter past, half past and
// quarter to (the V8 ACMMG170 half-hour scope extended with the quarter
// fractions this dedicated plugin drills).
const MINUTES = [0, 15, 30, 45] as const;

// Word form of h:m across the quarter-scale MINUTES set. "Quarter to" names
// the NEXT hour (12:45 is "quarter to 1").
function timeWords(h: number, m: number): string {
    if (m === 0) return `${h} o'clock`;
    if (m === 15) return `quarter past ${h}`;
    if (m === 30) return `half past ${h}`;
    return `quarter to ${(h % 12) + 1}`;
}

// Digital form ("3:00", "3:30") — the hour minute zero-padded.
function timeDigital(h: number, m: number): string {
    return `${h}:${m === 0 ? '00' : m}`;
}

// Which hour numeral the MINUTE hand points at for the quarter-scale minutes:
// 0 → 12, 15 → 3, 30 → 6, 45 → 9 (used in the teacher answer for draw items).
function minuteMark(m: number): number {
    return m === 0 ? 12 : (m / 15) * 3;
}

// Uppercases the first character so prompts opening with a word form
// ("half past 10 ...") read as sentences.
function sentence(text: string): string {
    return text.charAt(0).toUpperCase() + text.slice(1);
}

// Clock faces (V8 ACMMG170; V9 AC9M2M04). Kind pool is uniform across the
// sheet: two reading kinds (words / digital), one drawing kind (blank face)
// and two conversion kinds (words ↔ digital). Every item uses the same
// quarter-scale minute pool, so each mode drills all four positions.
function generateClock(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const mode = rng.pick(MODES);
        const h = rng.int(1, 12);
        const m = rng.pick(MINUTES);
        switch (mode) {
            case 'read-words': {
                // Clock WITH hands; the student writes the word form.
                out.push({
                    prompt: 'What time is shown on the clock?__',
                    answer: timeWords(h, m),
                    clock: { hour: h, minute: m },
                    // Word answers ("quarter past 11") need the wide blank.
                    wideBlanks: true
                });
                break;
            }
            case 'read-digital': {
                // Clock WITH hands; the student writes the digital form.
                out.push({
                    prompt: 'Write the digital time the clock shows:__',
                    answer: timeDigital(h, m),
                    clock: { hour: h, minute: m },
                    wideBlanks: true
                });
                break;
            }
            case 'draw': {
                // BLANK face (hands: false) — the student draws both hands on
                // it. The answer records the exact hand positions for marking.
                out.push({
                    prompt: sentence(`draw the hands to show ${timeWords(h, m)}.`),
                    answer: `${timeDigital(h, m)} — hour hand on ${h}, minute hand on ${minuteMark(m)}`,
                    clock: { hour: h, minute: m, hands: false }
                });
                break;
            }
            case 'words-to-digital': {
                // Word form → digital form (pure text, no clock figure). The
                // answer is written on a full-width line BELOW the prompt
                // (answerLine) — no inline "__" squeeze.
                out.push({
                    prompt: sentence(`${timeWords(h, m)} is the same time in digital:`),
                    answer: timeDigital(h, m),
                    answerLine: true
                });
                break;
            }
            default: {
                // 'digital-to-words': digital form → word form (pure text),
                // answered on the full-width line below the prompt.
                out.push({
                    prompt: sentence(`${timeDigital(h, m)} is the same time in words:`),
                    answer: timeWords(h, m),
                    answerLine: true
                });
                break;
            }
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const clockSpec: WorksheetSpec = {
    id: 'clock',
    label: 'Clock Faces',
    icon: '⏱',
    // Clocks need vertical room: 10 items per A4 page (2 columns × 5 rows).
    perPage: 10,
    offered: (grade: GradeConfig) => grade.available.includes('clock') && grade.caps.clockCap > 0,
    scope: (grade: GradeConfig) =>
        grade.caps.clockCap >= 12 ? "o'clock, half past, quarter past & to" : "o'clock & half past",
    generate: generateClock
};

// The plugin: a function the dashboard calls with its framework bundle.
export function ClockWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(clockSpec);
}
