// ─────────────────────────────────────────────────────────────────────────────
// COMPARE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `CompareWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Compare (>, <, =)', glyph '≟') and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// DEPTH-FIRST SHEET (quality over quantity): EIGHT connected tasks per A4
// page (single column — every prompt is a multi-part line with real writing
// space), instead of the old 24 bare "a __ b" sign drills. The sign stays,
// but now it is the START of the thinking: every pair is followed by "how
// far apart?" work, comparison of CALCULATED sides (sum vs number, sum vs
// sum), ordering three numbers, and a same-addend item solvable by pure
// relational reasoning without any calculation at all.
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Compare worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Comparison within opCap (Prep: within 10, Year 1: within 20, Year 2: 100).
//
// The task families. Every printed task carries 2–3 blanks whose answers are
// recorded in order in `answer` (comma separated — RawProblem allows it), so
// the answer key covers EVERY requested part:
//   signGap      — "a __ b; the difference between them is __" (sign AND gap)
//   sumSign      — "a + b __ c" (compute the left side first, then compare)
//   sumsSign     — "a + b __ c + d" (compute BOTH sides)
//   order        — three numbers written out least→greatest or greatest→least
//   sameAddend   — "a + b __ a + c" (the SAME addend on both sides: compare
//                  the OTHER addends — relational thinking, no calculating)
//
// NON-REPEATING SAMPLING: the family is dealt from a deck (every family
// appears before any repeats) and the whole question passes through
// sampleUnique keyed on the printed prompt, so a document holds each distinct
// line once before the space cycles.
const COMPARE_FORMS = ['signGap', 'sumSign', 'sumsSign', 'order', 'sameAddend'] as const;

// The printed sign for the two values (the model answer of every sign blank).
function signOf(a: number, b: number): string {
    return a > b ? '>' : a < b ? '<' : '=';
}

function generateComparison(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = caps.opCap;
    const formDeck = createDeck(rng, COMPARE_FORMS);
    return sampleUnique(
        count,
        () => {
            const form = formDeck.take();
            if (form === 'signGap') {
                // SIGN + GAP: distinct numbers so the gap is a real quantity
                // (0 would make the "=" case and the gap question collide).
                const a = rng.int(0, cap);
                let b = rng.int(0, cap - 1);
                // Draw b below the ceiling, then shift it up past `a` when it
                // landed on or above it: b stays <= cap AND can never equal a.
                if (b >= a) b = b + 1;
                return {
                    prompt: `${a} __ ${b}; the difference between them is __`,
                    answer: `${signOf(a, b)}, ${Math.abs(a - b)}`
                };
            }
            if (form === 'sumSign') {
                // COMPUTE THEN COMPARE: the sum stays within the grade's cap.
                const a = rng.int(1, Math.max(1, cap - 1));
                const b = rng.int(1, Math.max(1, cap - a)); // a + b <= cap
                const c = rng.int(0, cap);
                return { prompt: `${a} + ${b} __ ${c}`, answer: signOf(a + b, c) };
            }
            if (form === 'sumsSign') {
                // BOTH SIDES CALCULATED: each sum stays within the cap.
                const a = rng.int(1, Math.max(1, cap - 1));
                const b = rng.int(1, Math.max(1, cap - a));
                const c = rng.int(1, Math.max(1, cap - 1));
                const d = rng.int(1, Math.max(1, cap - c));
                return { prompt: `${a} + ${b} __ ${c} + ${d}`, answer: signOf(a + b, c + d) };
            }
            if (form === 'order') {
                // ORDER THREE: three DISTINCT numbers so the order is unique;
                // the direction alternates so "least/greatest" is read, not
                // assumed. The answer lists all three in the requested order.
                const pick = new Set<number>();
                while (pick.size < 3) pick.add(rng.int(0, cap));
                const nums = [...pick].sort((x, y) => x - y);
                const asc = rng.next() < 0.5;
                const shown = [...nums];
                // Shuffle the printed order deterministically (3 swaps).
                for (let i = 0; i < 3; i++) {
                    const j = rng.int(0, 2);
                    [shown[i], shown[j]] = [shown[j], shown[i]];
                }
                const wanted = asc ? nums : [...nums].reverse();
                return {
                    prompt: `Order ${shown.join(', ')} from ${asc ? 'least' : 'greatest'} to ${asc ? 'greatest' : 'least'}: __, __, __`,
                    answer: wanted.join(', ')
                };
            }
            // SAME ADDEND BOTH SIDES: a + b vs a + c — the student compares
            // b with c and IGNORES the shared addend (no sums needed).
            const a = rng.int(0, Math.max(0, cap - 1));
            const b = rng.int(0, cap - a); // a + b <= cap
            const cPool: number[] = [];
            for (let v = 0; v <= cap - a; v++) if (v !== b) cPool.push(v);
            const c = rng.pick(cPool); // b != c, so the sign is never "="
            return { prompt: `${a} + ${b} __ ${a} + ${c}`, answer: signOf(b, c) };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const comparisonSpec: WorksheetSpec = {
    id: 'comparison',
    label: 'Compare (>, <, =)',
    icon: '≟',
    // Eight connected multi-part tasks per A4, printed in ONE column so every
    // line has the full page width and the rows stretch to fill the sheet —
    // fewer questions, far more thinking and writing space each.
    perPage: 8,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('comparison'),
    scope: (grade: GradeConfig) => `within ${grade.caps.opCap}`,
    generate: generateComparison
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CompareWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(comparisonSpec);
}
