// ─────────────────────────────────────────────────────────────────────────────
// COMPASS DIRECTIONS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `CompassWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Compass Directions", glyph "✥") and which grades
//     offer it (a Year 1+ extension type; grade-1 level content — the four
//     cardinal directions only, no intercardinal points);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Questions are
//     prose-style (two-sentence turn/position items), so the sheet prints
//     single-column.
//
// Fully self-contained: the compass vocabulary lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Compass Directions
// worksheet without affecting the framework or any other plugin.
//
// CURRICULUM: grade-1 spatial sense (V8 ACMMG023 "give and follow directions
// to familiar places"; V9 AC9M1SP02) — recognise North, South, East and West,
// quarter/half turns between them, and everyday direction facts (sunrise,
// sunset, map orientation).
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// The four cardinal directions in CLOCKWISE compass order (N → E → S → W).
// Every index computation below relies on this order:
//   +1 mod 4 = quarter turn right / the direction on your right,
//   +3 mod 4 = quarter turn left  / the direction on your left,
//   +2 mod 4 = half turn / the opposite direction.
const COMPASS_POINTS = ['North', 'East', 'South', 'West'] as const;

// Kid names for the "walk there and back" kind (duplicated per plugin —
// plugins never import from each other).
const COMPASS_NAMES = ['Sam', 'Mia', 'Leo', 'Zoe', 'Tom', 'Max', 'Rae', 'Kai'] as const;

// One-line compass facts kids are expected to know. Fixed pool — dealt from a
// deck so the three facts spread evenly across a long document.
const COMPASS_FACTS: readonly [string, string][] = [
    ['Which direction does a compass needle always point?', 'North'],
    ['In which direction does the sun rise?', 'East'],
    ['In which direction does the sun set?', 'West']
];

// Map edges for the "map" kind: with North at the top of a map, East sits on
// the right (standard orientation) — so bottom = South, left = West.
const MAP_EDGES: readonly [string, string][] = [
    ['bottom', 'South'],
    ['left', 'West'],
    ['right', 'East']
];

// Compass directions (grade-1 spatial sense): quarter/half turns between the
// four cardinals, opposite pairs, left/right of a facing, map orientation,
// there-and-back walks and everyday direction facts. The generator ignores
// the grade caps — the N/S/E/W vocabulary is identical at every offered
// grade — and gates purely through the grade catalogue's `available` list.
//
// NON-REPEATING SAMPLING: facings, walk names and facts are dealt from decks
// (each element once per cycle) and the whole question passes through
// sampleUnique keyed on the printed prompt, so the same question never
// prints twice before the whole space (62 distinct prompts) has been dealt.
function generateCompass(rng: Rng, _caps: Caps, count: number): RawProblem[] {
    const faceDeck = createDeck(rng, COMPASS_POINTS);
    const nameDeck = createDeck(rng, COMPASS_NAMES);
    const factDeck = createDeck(rng, COMPASS_FACTS);
    return sampleUnique(
        count,
        () => {
            const kinds: string[] = [
                'turnRight',
                'turnLeft',
                'halfTurn',
                'opposite',
                'rightSide',
                'leftSide',
                'map',
                'walk',
                'fact'
            ];
            const kind = rng.pick(kinds);
            switch (kind) {
                case 'turnRight': {
                    // Quarter turn clockwise from the facing.
                    const i = COMPASS_POINTS.indexOf(faceDeck.take());
                    return {
                        prompt: `You are facing ${COMPASS_POINTS[i]}. You make a quarter turn to the right. What direction are you facing now?`,
                        answer: COMPASS_POINTS[(i + 1) % 4]
                    };
                }
                case 'turnLeft': {
                    // Quarter turn anti-clockwise from the facing.
                    const i = COMPASS_POINTS.indexOf(faceDeck.take());
                    return {
                        prompt: `You are facing ${COMPASS_POINTS[i]}. You make a quarter turn to the left. What direction are you facing now?`,
                        answer: COMPASS_POINTS[(i + 3) % 4]
                    };
                }
                case 'halfTurn': {
                    // A half turn lands on the opposite point.
                    const i = COMPASS_POINTS.indexOf(faceDeck.take());
                    return {
                        prompt: `You are facing ${COMPASS_POINTS[i]}. You make a half turn. What direction are you facing now?`,
                        answer: COMPASS_POINTS[(i + 2) % 4]
                    };
                }
                case 'opposite': {
                    const i = COMPASS_POINTS.indexOf(faceDeck.take());
                    return {
                        prompt: `What direction is the opposite of ${COMPASS_POINTS[i]}?`,
                        answer: COMPASS_POINTS[(i + 2) % 4]
                    };
                }
                case 'rightSide': {
                    // Facing d, the direction on your right is the clockwise
                    // neighbour (facing North → East on your right).
                    const i = COMPASS_POINTS.indexOf(faceDeck.take());
                    return {
                        prompt: `You are facing ${COMPASS_POINTS[i]}. What direction is on your right?`,
                        answer: COMPASS_POINTS[(i + 1) % 4]
                    };
                }
                case 'leftSide': {
                    const i = COMPASS_POINTS.indexOf(faceDeck.take());
                    return {
                        prompt: `You are facing ${COMPASS_POINTS[i]}. What direction is on your left?`,
                        answer: COMPASS_POINTS[(i + 3) % 4]
                    };
                }
                case 'map': {
                    const [edge, direction] = rng.pick(MAP_EDGES);
                    return {
                        prompt: `On a map, North is at the top. What direction is at the ${edge} of the map?`,
                        answer: direction
                    };
                }
                case 'walk': {
                    // Walking back the way you came = the opposite direction.
                    const i = COMPASS_POINTS.indexOf(faceDeck.take());
                    const name = nameDeck.take();
                    return {
                        prompt: `${name} walks to school towards the ${COMPASS_POINTS[i]}. On the way home, what direction is ${name} walking?`,
                        answer: COMPASS_POINTS[(i + 2) % 4]
                    };
                }
                default: {
                    const [prompt, answer] = factDeck.take();
                    return { prompt, answer };
                }
            }
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const compassSpec: WorksheetSpec = {
    id: 'compass',
    label: 'Compass Directions',
    icon: '✥',
    perPage: 12,
    // Two-sentence turn/position items — prints single-column like the
    // measurement sheet.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('compass'),
    // The N/S/E/W vocabulary is grade-1 level at every grade that offers it.
    scope: () => 'north, south, east & west',
    generate: generateCompass
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CompassWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(compassSpec);
}
