// ─────────────────────────────────────────────────────────────────────────────
// COMPARE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `CompareWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Compare (>, <, =)', glyph '≟') and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Compare worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Comparison: fill in >, < or = between two numbers within opCap.
function generateComparison(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const a = rng.int(0, caps.opCap);
        const b = rng.int(0, caps.opCap);
        const sign = a > b ? '>' : a < b ? '<' : '=';
        out.push({ prompt: `${a} __ ${b}`, answer: sign });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const comparisonSpec: WorksheetSpec = {
    id: 'comparison',
    label: 'Compare (>, <, =)',
    icon: '≟',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('comparison'),
    scope: (grade: GradeConfig) => `within ${grade.caps.opCap}`,
    generate: generateComparison
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CompareWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(comparisonSpec);
}
