// ─────────────────────────────────────────────────────────────────────────────
// COUNTING & NUMBERS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `CountingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Counting & Numbers', glyph '#') and which grades
//     offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Counting worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Counting & number recognition: "what comes next" or "what comes before".
// Both reduce to a single integer answer and stay within numCap.
function generateCounting(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        if (rng.next() < 0.5) {
            // Next number: a, a+1, __  => answer a+2 (a+2 must be <= numCap)
            const a = rng.int(0, Math.max(0, caps.numCap - 2));
            out.push({ prompt: `${a}, ${a + 1}, __`, answer: `${a + 2}` });
        } else {
            // Previous number: __, a, a+1  => answer a-1 (a-1 >= 0)
            const a = rng.int(1, Math.max(1, caps.numCap - 1));
            out.push({ prompt: `__, ${a}, ${a + 1}`, answer: `${a - 1}` });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const countingSpec: WorksheetSpec = {
    id: 'counting',
    label: 'Counting & Numbers',
    icon: '#',
    perPage: 18,
    offered: (grade: GradeConfig) => grade.available.includes('counting'),
    scope: (grade: GradeConfig) => `to ${grade.caps.numCap}`,
    generate: generateCounting
};

// The plugin: a function the dashboard calls with its framework bundle.
export function CountingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(countingSpec);
}
