// ─────────────────────────────────────────────────────────────────────────────
// DATA & TALLY WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `DataWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Data & Tally', glyph '▥') and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// QUALITY-OVER-QUANTITY REDESIGN (T2V): SIX large single-column items instead
// of ten cramped two-column ones, and every item is a CONNECTED task —
// observe the printed figure, then justify what it means:
//   - tally:  count the marks, THEN split the total into tens and ones;
//   - picture: read the "1 star = u things" scale, count the SVG stars, THEN
//     judge whether the amount beats 10 (a real comparison, not a trick —
//     the product is exact, so Yes/No is checkable);
//   - column: read the two given bar heights, name the winner, THEN compute
//     the difference (the difference is never drawn on the figure).
// The pictorial ASCII runs the old prompts printed ("||||/", "★★★★") are
// GONE from the question text — the SVG figure (framework/DataDiagram.tsx,
// enlarged by the framework) is now the only picture, and the prompts refer
// to "the tallies/stars below". Multi-part answers are comma-separated in
// printed blank order and cover every blank.
//
// Fully self-contained: the story vocabulary lives IN this plugin (duplicated
// deliberately — plugins never import from each other). Deleting this file
// and its line in plugins/index.ts removes the Data worksheet without
// affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Kid-friendly vocabulary (duplicated per plugin — plugins never import from
// each other; singular forms pair index-aligned with the plurals for
// "1 star = 1 apple" phrasing).
const NAMES = ['Sam', 'Mia', 'Leo', 'Zoe', 'Tom', 'Max', 'Rae', 'Kai'] as const;
const THINGS = ['apples', 'toys', 'stickers', 'balloons', 'cookies', 'crayons', 'flowers', 'cars'] as const;
const THINGS_SING = ['apple', 'toy', 'sticker', 'balloon', 'cookie', 'crayon', 'flower', 'car'] as const;

// Grammatical "1 ten / 2 tens" and "1 one / 3 ones" for the tally breakdown.
function tensWord(tens: number): string {
    return tens === 1 ? '1 ten' : `${tens} tens`;
}
function onesWord(ones: number): string {
    return ones === 1 ? '1 one' : `${ones} ones`;
}

// Data & tally (V8 ACMMG157-158 era; V9 AC9M1ST01/AC9M2ST01): count a classic
// five-tally (4 strokes + slash) in groups of five and decompose the total,
// scale a picture graph (1 star = u things) and compare it to 10, or read a
// column graph's winner AND the difference between the two bars.
//
// NON-REPEATING SAMPLING: names and thing pairs are dealt from decks and the
// whole question passes through sampleUnique keyed on the printed prompt
// PLUS the figure's counts — the observe-then-justify prompts are deliberately
// IDENTICAL sentences (the figure is the question), so the figure data is
// what makes two tallies of different totals distinct sampling keys.
function generateData(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(5, caps.dataCap);
    const nameDeck = createDeck(rng, NAMES);
    const thingDeck = createDeck(rng, THINGS.map((_, i) => i));
    return sampleUnique(
        count,
        () => {
            const r = rng.next();
            if (r < 0.4) {
                // Tally, then decompose: groups of five (drawn by the figure)
                // plus the remainder; the student counts them and states the
                // tens/ones split of the SAME total.
                const total = rng.int(3, cap);
                return {
                    prompt: `Count the tallies below. There are __ in all. That is __ tens and __ ones.`,
                    // Answer covers BOTH blanks: total, then its split.
                    answer: `${total}, ${tensWord(Math.floor(total / 10))} and ${onesWord(total % 10)}`,
                    // The figure owns the marks (tally groups of five).
                    data: { kind: 'tally', total }
                };
            }
            if (r < 0.7) {
                // Picture graph: each star counts for u things. Pick by index so we
                // can pair the plural (the sentence) with the singular ("1 star =
                // 1 apple") for grammatical counting language. The stars themselves
                // are the SVG figure — no Unicode run in the prompt.
                const u = rng.int(1, 3);
                const k = rng.int(1, 6);
                const idx = thingDeck.take();
                const plural = THINGS[idx];
                const singular = THINGS_SING[idx];
                const unit = u === 1 ? `1 ${singular}` : `${u} ${plural}`;
                const shown = k * u;
                return {
                    prompt: `In a picture graph, 1 star = ${unit}. Count the stars below. How many ${plural} do they show? __ Is that more than 10 ${plural}? Yes or No: __`,
                    // Both blanks: the scaled count, then the exact comparison.
                    answer: `${shown}, ${shown > 10 ? 'Yes' : 'No'}`,
                    // The figure draws exactly k stars (the scale lives in the
                    // prompt text, the total stays the student's job).
                    data: { kind: 'picture', stars: k }
                };
            }
            // Column graph: each square is 1 vote; name the winner THEN work
            // the difference. a >= 2 and b in [1, a-1] keep the "how many
            // more" difference strictly positive (never a 0-difference trick
            // question) and make n1 the unique "more votes" answer.
            const a = rng.int(2, Math.max(3, Math.floor(cap / 2)));
            const b = rng.int(1, a - 1);
            const squares = (n: number) => (n === 1 ? 'square' : 'squares');
            const n1 = nameDeck.take();
            // A second, different child (the deck of 8 keeps pairs distinct).
            let n2 = nameDeck.take();
            if (n2 === n1) n2 = nameDeck.take();
            if (n2 === n1) n2 = NAMES.find((n) => n !== n1)!;
            return {
                prompt: `In a column graph, each square is 1 vote. ${n1}'s bar is ${a} ${squares(a)} tall and ${n2}'s bar is ${b} ${squares(b)} tall. Who got MORE votes? __ How many more votes did ${n1} get? __`,
                // Both blanks: the winner, then the exact difference.
                answer: `${n1}, ${a - b}`,
                // The figure draws the two named bars (values stay in the
                // prompt; the difference is never drawn).
                data: { kind: 'column', leftName: n1, rightName: n2, left: a, right: b }
            };
        },
        // Composite key: identical sentences over different figures are
        // different questions (the figure carries the data).
        (p) => `${p.prompt}|${JSON.stringify(p.data)}`
    );
}

// The plugin's declarative spec (exported for its own tests).
export const dataSpec: WorksheetSpec = {
    id: 'data',
    label: 'Data & Tally',
    icon: '▥',
    // FOUR per A4 single-column (was ten two-column, then six): each item
    // prints its diagram (tally marks / picture stars / two named bars,
    // framework/DataDiagram.tsx) at full size with the two-part question and
    // its writing blanks on the same roomy row.
    // LAYOUT CAPACITY (T3M3): worst row = three prompt lines (3×21.6px) +
    // column-graph DataDiagram (6+100px) = 170.8px; at 6/page the 1fr row is
    // 132.4px and at 5/page 163.6px (both overflow), at 4/page 210.5px
    // (margin 39.7). See plugins/layout-capacity.test.ts for the model.
    perPage: 4,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('data'),
    scope: () => 'tallies & simple graphs',
    generate: generateData
};

// The plugin: a function the dashboard calls with its framework bundle.
export function DataWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(dataSpec);
}
