// ─────────────────────────────────────────────────────────────────────────────
// DIVISION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `DivisionWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Division", glyph "÷") and which grades offer it
//     (Year 2 only — division by equal sharing starts there);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Sharing stories
//     are worded, so the sheet prints single-column.
//
// Fully self-contained: the story vocabulary lives IN this plugin (duplicated
// deliberately — plugins never import from each other). Deleting this file
// and its line in plugins/index.ts removes the Division worksheet without
// affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Kid-friendly vocabulary (duplicated per plugin — plugins never import from
// each other).
const NAMES = ['Sam', 'Mia', 'Leo', 'Zoe', 'Tom', 'Max', 'Rae', 'Kai'] as const;
const THINGS = ['apples', 'toys', 'stickers', 'balloons', 'cookies', 'crayons', 'flowers', 'cars'] as const;

// Division by equal sharing & grouping (V8 Y2 multiplication/division; V9
// AC9M2N05). Three forms: the ÷ sign, a "share between friends" story, and a
// "put into groups of d" story. Divisors are >= 2 to avoid trivial x ÷ 1, and
// every dividend stays <= multCap * multCap (100 for Year 2). Only offered in
// Year 2 (buildDocument checks grade.available through the spec first).
function generateDivision(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const cap = Math.max(2, caps.multCap);
    for (let i = 0; i < count; i++) {
        const r = rng.next();
        const d = rng.int(2, cap); // divisor / friends / group size
        const q = rng.int(1, cap); // quotient
        if (r < 0.4) {
            out.push({ prompt: `${d * q} ÷ ${d} = __`, answer: `${q}` });
        } else if (r < 0.7) {
            const thing = rng.pick(THINGS);
            const n = rng.pick(NAMES);
            out.push({
                prompt: `${n} had ${d * q} ${thing}. ${n} shared them equally between ${d} friends. How many ${thing} does each friend get?`,
                answer: `${q}`
            });
        } else {
            const thing = rng.pick(THINGS);
            out.push({
                prompt: `There are ${d * q} ${thing}. They are put into groups of ${d}. How many groups are there?`,
                answer: `${q}`
            });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const divisionSpec: WorksheetSpec = {
    id: 'division',
    label: 'Division',
    icon: '÷',
    perPage: 12,
    // Sharing stories are worded — prints single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('division'),
    scope: (grade: GradeConfig) =>
        `equal sharing within ${Math.max(2, grade.caps.multCap) * Math.max(2, grade.caps.multCap)}`,
    generate: generateDivision
};

// The plugin: a function the dashboard calls with its framework bundle.
export function DivisionWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(divisionSpec);
}
