// ─────────────────────────────────────────────────────────────────────────────
// DOUBLES & NEAR DOUBLES WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `DoublesWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Doubles & Near Doubles', glyph '=') and which
//     grades offer it (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Doubles worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Doubles & near doubles (V9 AC9M2A02 / V8 "number facts to 20"): three forms
// — an exact double (a + a), a near double (a + a+1), or the worded "double
// of a". `doubleCap` bounds the base a (Y1: 10, Y2: 20).
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so a document holds each distinct line once
// before the space cycles (the old free-draw loop repeated "5 + 5 = __"
// twice within one page).
function generateDoubles(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(2, caps.doubleCap);
    return sampleUnique(
        count,
        () => {
            const r = rng.next();
            if (r < 0.4) {
                // Exact double.
                const a = rng.int(1, cap);
                return { prompt: `${a} + ${a} = __`, answer: `${a * 2}` };
            }
            if (r < 0.7) {
                // Near double: a + (a+1) = 2a + 1. a+1 must stay within the cap.
                const a = rng.int(1, cap - 1);
                return { prompt: `${a} + ${a + 1} = __`, answer: `${a + a + 1}` };
            }
            // Worded doubling (the verbal form teachers drill in Y1/Y2).
            const a = rng.int(1, cap);
            return { prompt: `What is double ${a}?`, answer: `${a * 2}` };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const doublesSpec: WorksheetSpec = {
    id: 'doubles',
    label: 'Doubles & Near Doubles',
    icon: '=',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('doubles'),
    scope: (grade: GradeConfig) => `doubles to ${Math.max(2, grade.caps.doubleCap)}`,
    generate: generateDoubles
};

// The plugin: a function the dashboard calls with its framework bundle.
export function DoublesWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(doublesSpec);
}
