// ─────────────────────────────────────────────────────────────────────────────
// DOUBLES & NEAR DOUBLES WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `DoublesWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Doubles & Near Doubles', glyph '=') and which
//     grades offer it (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// DEPTH-FIRST SHEET (quality over quantity): EIGHT connected tasks per A4
// page (single column — every prompt is a multi-part line with real writing
// space), instead of the old 24 isolated single-blank recalls. The whole
// point of doubles is that they CHAIN into other facts, so every task now
// prints the chain: double then near double, double then halving (the
// inverse pair), two doubles then how far apart they are, doubling twice,
// and a halving claim to check before the doubling answer is written.
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Doubles worksheet without affecting the framework or any other
// plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Doubles & near doubles (V9 AC9M2A02 / V8 "number facts to 20") over the
// fact space doubleCap bounds the base a (Y1: 10, Y2: 20).
//
// The task families. Every printed task carries 2–3 blanks whose answers are
// recorded in order in `answer` (comma separated — RawProblem allows it), so
// the answer key covers EVERY requested part:
//   nearChain   — "a + a = __ and a + (a+1) = __"  (the near-double strategy)
//   halfFamily  — "Double a is __ and half of 2a is __" (the inverse pair)
//   doubleDiff  — two doubles then "the doubles differ by __" (always even —
//                 the student notices doubles move in twos)
//   nearMissing — "a + __ = 2a+1 and a + a = __"   (missing near-double part)
//   doubleTwice — "Double a is __ and double that number is __" (chaining
//                 doubling; 4a stays within 2 x doubleCap, the sheet's
//                 established ceiling for halving/doubling values)
//   verifyHalf  — "True or false: half of 2a is h. __; double a is __"
//                 (checking the inverse claim, then the matching double)
//
// NON-REPEATING SAMPLING: the family is dealt from a deck (every family
// appears before any repeats) and the whole question passes through
// sampleUnique keyed on the printed prompt, so each fact prints once per
// FORM before the space cycles.
const DOUBLES_FORMS = ['nearChain', 'halfFamily', 'doubleDiff', 'nearMissing', 'doubleTwice', 'verifyHalf'] as const;

function generateDoubles(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(2, caps.doubleCap);
    const formDeck = createDeck(rng, DOUBLES_FORMS);
    return sampleUnique(
        count,
        () => {
            const form = formDeck.take();
            if (form === 'nearChain') {
                // DOUBLE, then STEP ON by one: the near double is the double
                // plus one — the strategy the pair teaches.
                const a = rng.int(1, cap - 1); // a+1 stays within the cap
                return {
                    prompt: `${a} + ${a} = __ and ${a} + ${a + 1} = __`,
                    answer: `${2 * a}, ${2 * a + 1}`
                };
            }
            if (form === 'halfFamily') {
                // THE INVERSE PAIR: doubling and halving the same number.
                const a = rng.int(1, cap);
                return {
                    prompt: `Double ${a} is __ and half of ${2 * a} is __`,
                    answer: `${2 * a}, ${a}`
                };
            }
            if (form === 'doubleDiff') {
                // TWO DOUBLES, THEN THE GAP: distinct bases so the gap is a
                // positive even number the student can predict from the
                // bases alone (2 x the base gap).
                const a = rng.int(1, cap);
                let b = rng.int(1, cap - 1);
                if (b >= a) b = b + 1; // shift past a: b <= cap and b != a
                return {
                    prompt: `${a} + ${a} = __ and ${b} + ${b} = __; the doubles differ by __`,
                    answer: `${2 * a}, ${2 * b}, ${2 * Math.abs(a - b)}`
                };
            }
            if (form === 'nearMissing') {
                // NEAR-DOUBLE MISSING PART: the total 2a+1 forces the blank
                // to be a+1 — then the plain double underneath is named.
                const a = rng.int(1, cap - 1);
                return {
                    prompt: `${a} + __ = ${2 * a + 1} and ${a} + ${a} = __`,
                    answer: `${a + 1}, ${2 * a}`
                };
            }
            if (form === 'doubleTwice') {
                // DOUBLE THE DOUBLE: 4a <= 2 x cap, the same ceiling the
                // halving items already used ("half of 2a" with 2a <= 2 x cap).
                const a = rng.int(1, Math.max(1, Math.floor(cap / 2)));
                return {
                    prompt: `Double ${a} is __ and double that number is __`,
                    answer: `${2 * a}, ${4 * a}`
                };
            }
            // VERIFY THE HALVING, then state the double. The claim is correct
            // ~1/3 of the time; a wrong claim is off by one half.
            const a = rng.int(1, cap);
            let claim = a;
            if (rng.next() < 2 / 3) {
                const delta = rng.next() < 0.5 ? 1 : -1;
                claim = a + delta >= 1 && a + delta <= cap ? a + delta : a - 1;
            }
            return {
                prompt: `True or false: half of ${2 * a} is ${claim}. __; double ${a} is __`,
                answer: `${claim === a ? 'Correct' : 'Wrong'}, ${2 * a}`,
                // The first blank takes the WORD ("Correct"/"Wrong").
                wideBlanks: true
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const doublesSpec: WorksheetSpec = {
    id: 'doubles',
    label: 'Doubles & Near Doubles',
    icon: '=',
    // Eight connected multi-part tasks per A4, printed in ONE column so every
    // line has the full page width and the rows stretch to fill the sheet —
    // fewer questions, far more thinking and writing space each.
    perPage: 8,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('doubles'),
    scope: (grade: GradeConfig) => `doubles to ${Math.max(2, grade.caps.doubleCap)}`,
    generate: generateDoubles
};

// The plugin: a function the dashboard calls with its framework bundle.
export function DoublesWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(doublesSpec);
}
