// ─────────────────────────────────────────────────────────────────────────────
// MEASUREMENT WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `MeasurementWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Measurement", glyph "↔") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Questions mix
//     short items with worded ones, so the sheet prints single-column.
//
// Fully self-contained: the measurement item catalogue lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Measurement worksheet
// without affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Measurement items with reference values (V8 informal units + cm). `len` is
// length in cm, `mass` in grams, `cap` capacity in mL; 0 = not used for that
// comparison category. Only items with a non-zero value participate in a
// category's comparison pools.
type MeasureItem = { name: string; len: number; mass: number; cap: number };
const MEASURE_ITEMS: MeasureItem[] = [
    { name: 'finger', len: 5, mass: 0, cap: 0 },
    { name: 'crayon', len: 10, mass: 5, cap: 0 },
    { name: 'pencil', len: 15, mass: 10, cap: 0 },
    { name: 'notebook', len: 22, mass: 200, cap: 0 },
    { name: 'ruler', len: 30, mass: 25, cap: 0 },
    { name: 'table', len: 75, mass: 8000, cap: 0 },
    { name: 'door', len: 200, mass: 30000, cap: 0 },
    { name: 'apple', len: 0, mass: 150, cap: 0 },
    { name: 'water bottle', len: 0, mass: 500, cap: 1000 },
    { name: 'book', len: 0, mass: 600, cap: 0 },
    { name: 'cat', len: 0, mass: 4000, cap: 0 },
    { name: 'bowling ball', len: 0, mass: 6500, cap: 0 },
    { name: 'spoon', len: 0, mass: 8, cap: 15 },
    { name: 'cup', len: 0, mass: 50, cap: 250 },
    { name: 'bucket', len: 0, mass: 170, cap: 5000 },
    { name: 'tank', len: 0, mass: 0, cap: 100000 }
];
// Categories: which item field holds the value + the exact question sentence
// (capacity can't use the "Which is <word>" pattern, hence per-category text).
const MEASURE_CATEGORIES = {
    length: { field: 'len', ask: (a: string, b: string) => `Which is longer: the ${a} or the ${b}?` },
    mass: { field: 'mass', ask: (a: string, b: string) => `Which is heavier: the ${a} or the ${b}?` },
    capacity: { field: 'cap', ask: (a: string, b: string) => `Which holds more: the ${a} or the ${b}?` }
} as const;
type MeasureCategory = keyof typeof MEASURE_CATEGORIES;
// Length pairs whose values divide evenly (ratio 2..5) — used by the
// "about how many <small> long is the <big>?" informal-units questions.
type MeasurePair = { big: MeasureItem; small: MeasureItem };
const MEASURE_RATIO_PAIRS: MeasurePair[] = (() => {
    const pairs: MeasurePair[] = [];
    for (const a of MEASURE_ITEMS) {
        for (const b of MEASURE_ITEMS) {
            if (a.len === 0 || b.len === 0 || a.len <= b.len) continue;
            const r = a.len / b.len;
            if (r >= 2 && r <= 5 && a.len % b.len === 0) pairs.push({ big: a, small: b });
        }
    }
    return pairs;
})();

// Measurement sense (V8 ACMMG171-173; V9 AC9M1M01-02): compare items on
// length/mass/capacity, count how many small units make a big one (uniform
// informal units), and — Year 2 only (metricCap > 0) — compare a measured
// length to a metre.
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so the same comparison pair never prints
// twice in a row and the (category x item pair x ratio) space is spread
// evenly before any repeats.
function generateMeasure(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const metric = caps.metricCap > 0;
    const cats: MeasureCategory[] = ['length', 'mass', 'capacity'];
    return sampleUnique(
        count,
        () => {
            // Comparison items are always available; the two metric items only for
            // grades with metricCap > 0 (Year 2).
            const kinds: string[] = metric ? ['compare', 'compare', 'compare', 'ratio', 'metre'] : ['compare'];
            const kind = rng.pick(kinds);
            if (kind === 'compare') {
                const cat = rng.pick(cats);
                // `field` resolves to 'len' | 'mass' | 'cap' (numeric keys only),
                // so item comparisons below are number-vs-number.
                const field: 'len' | 'mass' | 'cap' = MEASURE_CATEGORIES[cat].field;
                const pool = MEASURE_ITEMS.filter((it) => it[field] > 0);
                const a = rng.pick(pool);
                // Pick a distinct item with a DIFFERENT value so the answer is
                // never a tie.
                let b = rng.pick(pool);
                while (b === a || b[field] === a[field]) b = rng.pick(pool);
                const bigger = a[field] > b[field] ? a : b;
                // Per-category question sentence (capacity reads "holds more", not
                // "is holds more").
                return { prompt: MEASURE_CATEGORIES[cat].ask(a.name, b.name), answer: bigger.name };
            }
            if (kind === 'ratio') {
                // Uniform informal units: "about how many <small> long is the <big>"
                // (only pairs with an integer ratio 2..5, precomputed at module load).
                const p = rng.pick(MEASURE_RATIO_PAIRS);
                const r = p.big.len / p.small.len;
                return {
                    prompt: `A ${p.big.name} is about ${p.big.len} cm long. A ${p.small.name} is about ${p.small.len} cm long. About how many ${p.small.name}s long is a ${p.big.name}?`,
                    answer: `${r}`
                };
            }
            // Year 2: compare a measured length to a metre (100 cm).
            const pool = MEASURE_ITEMS.filter((it) => it.len > 0);
            const it = rng.pick(pool);
            return {
                prompt: `A ${it.name} is about ${it.len} cm long. Is it longer or shorter than a metre?`,
                answer: it.len < 100 ? 'shorter' : 'longer'
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const measureSpec: WorksheetSpec = {
    id: 'measure',
    label: 'Measurement',
    icon: '↔',
    perPage: 12,
    // Mixes short comparisons with worded items — prints single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('measure'),
    scope: (grade: GradeConfig) => (grade.caps.metricCap > 0 ? 'informal & metric units' : 'informal units'),
    generate: generateMeasure
};

// The plugin: a function the dashboard calls with its framework bundle.
export function MeasurementWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(measureSpec);
}
