// ─────────────────────────────────────────────────────────────────────────────
// MEASUREMENT WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `MeasurementWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Measurement", glyph "↔") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Questions mix
//     short items with worded ones, so the sheet prints single-column.
//
// Fully self-contained: the measurement item catalogue lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Measurement worksheet
// without affecting the framework or any other plugin.
//
// DEPTH DESIGN (quality over quantity): six connected items per page instead
// of twelve isolated "which is bigger" answers. The item families:
//   compare        — the classic direct comparison (kept for reading fluency);
//   compare+ratio  — WHICH is longer, then ABOUT HOW MANY smalls fit the big
//                    one (uniform-unit iteration on the SAME pair);
//   orderThree     — three items, name the least AND the greatest (conservation
//                    of the attribute across a set, not just a pair);
//   trips          — practical capacity reasoning: which unit needs MORE trips
//                    to fill the big container, then which unit holds more;
//   metreGap (Y2)  — compare a cm length to a metre, then quantify the gap in
//                    cm (comparison → measurement);
//   sensibleUnit   — is a pencil 15 cm, 15 m or 15 kg? (unit-choice sense).
// Every item's answer string carries BOTH part results in printed order.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Measurement items with reference values (V8 informal units + cm). `len` is
// length in cm, `mass` in grams, `cap` capacity in mL; 0 = not used for that
// comparison category. Only items with a non-zero value participate in a
// category's comparison pools.
type MeasureItem = { name: string; len: number; mass: number; cap: number };
const MEASURE_ITEMS: MeasureItem[] = [
    { name: 'finger', len: 5, mass: 0, cap: 0 },
    { name: 'crayon', len: 10, mass: 5, cap: 0 },
    { name: 'pencil', len: 15, mass: 10, cap: 0 },
    { name: 'notebook', len: 22, mass: 200, cap: 0 },
    { name: 'ruler', len: 30, mass: 25, cap: 0 },
    { name: 'table', len: 75, mass: 8000, cap: 0 },
    { name: 'door', len: 200, mass: 30000, cap: 0 },
    { name: 'apple', len: 0, mass: 150, cap: 0 },
    { name: 'water bottle', len: 0, mass: 500, cap: 1000 },
    { name: 'book', len: 0, mass: 600, cap: 0 },
    { name: 'cat', len: 0, mass: 4000, cap: 0 },
    { name: 'bowling ball', len: 0, mass: 6500, cap: 0 },
    { name: 'spoon', len: 0, mass: 8, cap: 15 },
    { name: 'cup', len: 0, mass: 50, cap: 250 },
    { name: 'bucket', len: 0, mass: 170, cap: 5000 },
    { name: 'tank', len: 0, mass: 0, cap: 100000 }
];
// Categories: which item field holds the value + the exact question sentence
// (capacity can't use the "Which is <word>" pattern, hence per-category text).
// The low/high superlatives drive the three-item ordering items.
const MEASURE_CATEGORIES = {
    // `low`/`high` are grammatical fragments completing "Which …?" — verb
    // forms differ per category ("is the shortest" vs "holds the least").
    length: {
        field: 'len',
        ask: (a: string, b: string) => `Which is longer: the ${a} or the ${b}?`,
        noun: 'length',
        low: 'is the shortest',
        high: 'is the longest'
    },
    mass: {
        field: 'mass',
        ask: (a: string, b: string) => `Which is heavier: the ${a} or the ${b}?`,
        noun: 'mass',
        low: 'is the lightest',
        high: 'is the heaviest'
    },
    capacity: {
        field: 'cap',
        ask: (a: string, b: string) => `Which holds more: the ${a} or the ${b}?`,
        noun: 'capacity',
        low: 'holds the least',
        high: 'holds the most'
    }
} as const;
type MeasureCategory = keyof typeof MEASURE_CATEGORIES;
// Length pairs whose values divide evenly (ratio 2..5) — used by the
// "about how many <small> long is the <big>?" informal-units questions.
type MeasurePair = { big: MeasureItem; small: MeasureItem };
const MEASURE_RATIO_PAIRS: MeasurePair[] = (() => {
    const pairs: MeasurePair[] = [];
    for (const a of MEASURE_ITEMS) {
        for (const b of MEASURE_ITEMS) {
            if (a.len === 0 || b.len === 0 || a.len <= b.len) continue;
            const r = a.len / b.len;
            if (r >= 2 && r <= 5 && a.len % b.len === 0) pairs.push({ big: a, small: b });
        }
    }
    return pairs;
})();
// Capacity triples for the "more trips" reasoning item: (small, smaller, big)
// with small < smaller < big by capacity — the smaller the carrying unit, the
// MORE trips the big container needs. Built once, deterministic.
const TRIP_TRIPLES: { small: MeasureItem; smaller: MeasureItem; big: MeasureItem }[] = (() => {
    const caps = MEASURE_ITEMS.filter((it) => it.cap > 0);
    const out: { small: MeasureItem; smaller: MeasureItem; big: MeasureItem }[] = [];
    for (const big of caps) {
        for (const small of caps) {
            for (const smaller of caps) {
                if (small.cap < smaller.cap && smaller.cap < big.cap) out.push({ small, smaller, big });
            }
        }
    }
    return out;
})();
// Items short enough for the cm-vs-m unit-sense item (a "15 m pencil" is
// obviously silly at this age; a "2 m ruler" is not).
const SHORT_ITEMS = MEASURE_ITEMS.filter((it) => it.len > 0 && it.len <= 30);

// Measurement sense (V8 ACMMG171-173; V9 AC9M1M01-02): compare items on
// length/mass/capacity, iterate uniform informal units, order a set, reason
// about measuring with units, and — Year 2 only (metricCap > 0) — place cm
// lengths against a metre and choose sensible units.
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so the same comparison pair never prints
// twice in a row and the (category × item set × ratio) space is spread
// evenly before any repeats.
function generateMeasure(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const metric = caps.metricCap > 0;
    const cats: MeasureCategory[] = ['length', 'mass', 'capacity'];
    return sampleUnique(
        count,
        () => {
            // Comparison-family items are always available; the two metric
            // items only for grades with metricCap > 0 (Year 2). 'compare' is
            // weighted so the finite reasoning/ratio prompts never dominate.
            const kinds: string[] = metric
                ? ['compare', 'compare', 'ratio', 'order', 'trips', 'metre', 'unit']
                : ['compare', 'compare', 'ratio', 'order', 'trips'];
            const kind = rng.pick(kinds);
            if (kind === 'compare') {
                const cat = rng.pick(cats);
                // `field` resolves to 'len' | 'mass' | 'cap' (numeric keys only),
                // so item comparisons below are number-vs-number.
                const field: 'len' | 'mass' | 'cap' = MEASURE_CATEGORIES[cat].field;
                const pool = MEASURE_ITEMS.filter((it) => it[field] > 0);
                const a = rng.pick(pool);
                // Pick a distinct item with a DIFFERENT value so the answer is
                // never a tie.
                let b = rng.pick(pool);
                while (b === a || b[field] === a[field]) b = rng.pick(pool);
                const bigger = a[field] > b[field] ? a : b;
                return { prompt: MEASURE_CATEGORIES[cat].ask(a.name, b.name), answer: bigger.name };
            }
            if (kind === 'ratio') {
                // Connected pair: WHICH is longer, then ABOUT HOW MANY of the
                // small one iterate into the big one (integer ratio 2..5,
                // precomputed at module load — never a fractional estimate).
                const p = rng.pick(MEASURE_RATIO_PAIRS);
                const r = p.big.len / p.small.len;
                return {
                    prompt:
                        `A ${p.big.name} is about ${p.big.len} cm long. A ${p.small.name} is about ${p.small.len} cm long.\n` +
                        `(a) Which is longer: the ${p.small.name} or the ${p.big.name}? __\n` +
                        `(b) About how many ${p.small.name}s long is a ${p.big.name}? __`,
                    answer: `${p.big.name}, ${r}`
                };
            }
            if (kind === 'order') {
                // Three items, one attribute: name the EXTREMES (least AND
                // greatest) — ordering sense without writing a full list.
                const cat = rng.pick(cats);
                const field: 'len' | 'mass' | 'cap' = MEASURE_CATEGORIES[cat].field;
                const pool = MEASURE_ITEMS.filter((it) => it[field] > 0);
                const a = rng.pick(pool);
                let b = rng.pick(pool);
                while (b === a) b = rng.pick(pool);
                let c = rng.pick(pool);
                while (c === a || c === b) c = rng.pick(pool);
                const sorted = [a, b, c].sort((x, y) => x[field] - y[field]);
                const { noun, low, high } = MEASURE_CATEGORIES[cat];
                return {
                    prompt:
                        `The ${a.name}, the ${b.name} and the ${c.name} are compared by ${noun}.\n` +
                        `(a) Which ${low}? __\n` +
                        `(b) Which ${high}? __`,
                    answer: `${sorted[0].name}, ${sorted[2].name}`
                };
            }
            if (kind === 'trips') {
                // Practical capacity reasoning: the SMALLER the carrying unit,
                // the MORE trips; then the unit comparison it rests on.
                const t = rng.pick(TRIP_TRIPLES);
                return {
                    prompt:
                        `You empty the full ${t.big.name} using a ${t.smaller.name} or a ${t.small.name}.\n` +
                        `(a) Which needs MORE trips: the ${t.smaller.name} or the ${t.small.name}? __\n` +
                        `(b) Which holds more: the ${t.small.name} or the ${t.smaller.name}? __`,
                    answer: `${t.small.name}, ${t.smaller.name}`
                };
            }
            if (kind === 'metre') {
                // Year 2: compare a measured length to a metre (100 cm), then
                // QUANTIFY the gap in cm (comparison → measurement).
                const pool = MEASURE_ITEMS.filter((it) => it.len > 0);
                const it = rng.pick(pool);
                const shorter = it.len < 100;
                return {
                    prompt:
                        `A ${it.name} is about ${it.len} cm long.\n` +
                        `(a) Is it longer or shorter than a metre? __\n` +
                        `(b) How many cm ${shorter ? 'shorter' : 'longer'} than a metre is it? __`,
                    answer: `${shorter ? 'shorter' : 'longer'}, ${Math.abs(100 - it.len)}`
                };
            }
            // 'unit' (Year 2): choose the sensible unit for a familiar object
            // — same NUMBER, three units, only one is ever sensible.
            const it = rng.pick(SHORT_ITEMS);
            return {
                prompt: `Which is about right for the length of a ${it.name}: ${it.len} cm, ${it.len} m or ${it.len} kg? __`,
                answer: `${it.len} cm`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const measureSpec: WorksheetSpec = {
    id: 'measure',
    label: 'Measurement',
    icon: '↔',
    // Six connected items per page: multi-part prompts need the working space
    // the density reduction frees up.
    perPage: 6,
    // Mixes short comparisons with worded items — prints single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('measure'),
    scope: (grade: GradeConfig) => (grade.caps.metricCap > 0 ? 'informal & metric units' : 'informal units'),
    generate: generateMeasure
};

// The plugin: a function the dashboard calls with its framework bundle.
export function MeasurementWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(measureSpec);
}
