// ─────────────────────────────────────────────────────────────────────────────
// MISSING NUMBER WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `MissingNumberWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Missing Number", glyph "?") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Missing Number worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Missing number / number bond: a + __ = c  or  __ + a = c  (c within opCap,
// the hidden addend is always >= 0 because a is chosen <= c).
function generateMissing(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    for (let i = 0; i < count; i++) {
        const c = rng.int(1, caps.opCap); // the sum
        const a = rng.int(0, c); // one known addend
        const missing = c - a; // always >= 0
        const prompt = rng.next() < 0.5 ? `${a} + __ = ${c}` : `__ + ${a} = ${c}`;
        out.push({ prompt, answer: `${missing}` });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const missingSpec: WorksheetSpec = {
    id: 'missing',
    label: 'Missing Number',
    icon: '?',
    perPage: 16,
    offered: (grade: GradeConfig) => grade.available.includes('missing'),
    scope: (grade: GradeConfig) => `within ${grade.caps.opCap}`,
    generate: generateMissing
};

// The plugin: a function the dashboard calls with its framework bundle.
export function MissingNumberWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(missingSpec);
}
