// ─────────────────────────────────────────────────────────────────────────────
// COINS & MONEY WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `MoneyWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Coins & Money', glyph '$') and which grades offer it
//     (Year 2 only — Australian coins are V8 Y2 content);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Money questions
//     are worded, so the sheet prints single-column.
//
// Fully self-contained: the Australian coin catalogue lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Money worksheet
// without affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Australian coin denominations (V8 Y2: form amounts to $10 with coins & notes;
// V9 moves cents to Y3, so this sheet is V8-aligned — see the grade catalogue).
const AU_COIN_CENTS = [5, 10, 20, 50] as const;
const AU_COIN_WORDS = ['five-cent', 'ten-cent', 'twenty-cent', 'fifty-cent'] as const;
const AU_NOTE_DOLLARS = [1, 2, 5] as const;
// Format a cents amount the way a worksheet prints it: 85c or $1.50.
function formatMoney(cents: number): string {
    return cents >= 100 ? `$${Math.floor(cents / 100)}.${String(cents % 100).padStart(2, '0')}` : `${cents}c`;
}

// Australian coins & money (V8 Y2: form amounts with 5c/10c/20c/50c coins and
// notes; V9 moves cents to Y3 — this sheet is V8-aligned, see grades.ts).
// Four forms: make an amount with the canonical fewest coins, total a jar of
// same-denomination coins, "how many <coin> make <amount>?", and a note +
// coin combination.
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so each distinct amount/coin-count line
// prints once before the space cycles.
function generateMoney(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(5, caps.coinCap);
    return sampleUnique(
        count,
        () => {
            const r = rng.next();
            if (r < 0.4) {
                // Make the amount: multiples of 5c up to the cap, answered with
                // the canonical coin set (greedy 50/20/10/5 = fewest coins).
                const amount = 5 * rng.int(1, Math.floor(cap / 5));
                const coinList: string[] = [];
                let rem = amount;
                for (const c of [50, 20, 10, 5]) {
                    const n = Math.floor(rem / c);
                    for (let k = 0; k < n; k++) coinList.push(`${c}c`);
                    rem -= n * c;
                }
                return { prompt: `What coins make ${formatMoney(amount)}?`, answer: coinList.join(' + ') };
            }
            if (r < 0.65) {
                // A jar of one denomination — a skip-counting-in-money task. The
                // coin count is capped at 9: "16 five-cent coins" is a fine fact
                // but a tedious count for the grade's counting fluency goal.
                const c = rng.pick(AU_COIN_CENTS);
                const word = AU_COIN_WORDS[AU_COIN_CENTS.indexOf(c)];
                const n = rng.int(1, Math.max(1, Math.min(9, Math.floor(cap / c))));
                return { prompt: `A jar holds ${n} ${word} coins. How much money is in the jar?`, answer: formatMoney(n * c) };
            }
            if (r < 0.85) {
                // How many of one coin make a round amount.
                const c = rng.pick(AU_COIN_CENTS);
                const word = AU_COIN_WORDS[AU_COIN_CENTS.indexOf(c)];
                const k = rng.int(1, Math.max(1, Math.min(4, Math.floor(cap / c))));
                return { prompt: `How many ${word} coins make ${formatMoney(k * c)}?`, answer: `${k}` };
            }
            // A note plus one coin: total printed as dollars.cents.
            const note = rng.pick(AU_NOTE_DOLLARS);
            const cent = rng.pick(AU_COIN_CENTS);
            const word = AU_COIN_WORDS[AU_COIN_CENTS.indexOf(cent)];
            return {
                prompt: `You have one $${note} note and one ${word} coin. How much money is there in all?`,
                answer: formatMoney(note * 100 + cent)
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const moneySpec: WorksheetSpec = {
    id: 'money',
    label: 'Coins & Money',
    icon: '$',
    perPage: 12,
    // Money questions are worded — prints single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('money'),
    scope: (grade: GradeConfig) => `coins up to $${Math.max(1, Math.round(grade.caps.coinCap / 100))}`,
    generate: generateMoney
};

// The plugin: a function the dashboard calls with its framework bundle.
export function MoneyWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(moneySpec);
}
