// ─────────────────────────────────────────────────────────────────────────────
// COINS & MONEY WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `MoneyWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Coins & Money', glyph '$') and which grades offer it
//     (Year 2 only — Australian coins are V8 Y2 content);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Money questions
//     are worded, so the sheet prints single-column.
//
// Fully self-contained: the Australian coin catalogue lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Money worksheet
// without affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Australian coin denominations (V8 Y2: form amounts to $10 with coins & notes;
// V9 moves cents to Y3, so this sheet is V8-aligned — see the grade catalogue).
const AU_COIN_CENTS = [5, 10, 20, 50] as const;
const AU_COIN_WORDS = ['five-cent', 'ten-cent', 'twenty-cent', 'fifty-cent'] as const;
const AU_NOTE_DOLLARS = [1, 2, 5] as const;
// Format a cents amount the way a worksheet prints it: 85c or $1.50.
function formatMoney(cents: number): string {
    return cents >= 100 ? `$${Math.floor(cents / 100)}.${String(cents % 100).padStart(2, '0')}` : `${cents}c`;
}

// Australian coins & money (V8 Y2: form amounts with 5c/10c/20c/50c coins and
// notes; V9 moves cents to Y3 — this sheet is V8-aligned, see grades.ts).
// FIVE forms over the small coin-amount space — the amount range is limited
// (multiples of 5c to coinCap), so the form variants are what keep a long
// document fresh:
//   0. make the amount:      "What coins make 85c?"  (canonical fewest coins)
//   1. jar of one coin type: "A jar holds n ten-cent coins. How much money
//                             is in the jar?"
//   2. how many coins:       "How many twenty-cent coins make $1.00?"
//   3. note + coin total:   "You have one $2 note and one fifty-cent coin..."
//   4. coin swap:           "How many 5c coins are the same as one 20c
//                             coin?" (equivalence — a distinct Y2 skill)
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so each amount/count prints once per FORM
// before the space cycles.
function generateMoney(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(5, caps.coinCap);
    return sampleUnique(
        count,
        () => {
            const form = rng.int(0, 4);
            if (form === 0) {
                // Make the amount: multiples of 5c up to the cap, answered with
                // the canonical coin set (greedy 50/20/10/5 = fewest coins).
                const amount = 5 * rng.int(1, Math.floor(cap / 5));
                const coinList: string[] = [];
                let rem = amount;
                for (const c of [50, 20, 10, 5]) {
                    const n = Math.floor(rem / c);
                    for (let k = 0; k < n; k++) coinList.push(`${c}c`);
                    rem -= n * c;
                }
                return { prompt: `What coins make ${formatMoney(amount)}?`, answer: coinList.join(' + ') };
            }
            if (form === 1) {
                // A jar of one denomination — a skip-counting-in-money task. The
                // coin count is capped at 9: "16 five-cent coins" is a fine fact
                // but a tedious count for the grade's counting fluency goal.
                const c = rng.pick(AU_COIN_CENTS);
                const word = AU_COIN_WORDS[AU_COIN_CENTS.indexOf(c)];
                const n = rng.int(1, Math.max(1, Math.min(9, Math.floor(cap / c))));
                return { prompt: `A jar holds ${n} ${word} coins. How much money is in the jar?`, answer: formatMoney(n * c) };
            }
            if (form === 2) {
                // How many of one coin make a round amount.
                const c = rng.pick(AU_COIN_CENTS);
                const word = AU_COIN_WORDS[AU_COIN_CENTS.indexOf(c)];
                const k = rng.int(1, Math.max(1, Math.min(4, Math.floor(cap / c))));
                return { prompt: `How many ${word} coins make ${formatMoney(k * c)}?`, answer: `${k}` };
            }
            if (form === 3) {
                // A note plus one coin: total printed as dollars.cents.
                const note = rng.pick(AU_NOTE_DOLLARS);
                const cent = rng.pick(AU_COIN_CENTS);
                const word = AU_COIN_WORDS[AU_COIN_CENTS.indexOf(cent)];
                return {
                    prompt: `You have one $${note} note and one ${word} coin. How much money is there in all?`,
                    answer: formatMoney(note * 100 + cent)
                };
            }
            // Coin swap: how many small coins equal one bigger coin (only
            // pairs where the big coin divides evenly by the small one).
            const pairs: [number, number][] = [10, 20, 50].flatMap((big) =>
                [5, 10, 20].filter((small) => small < big && big % small === 0).map((small) => [small, big] as [number, number])
            );
            const [small, big] = rng.pick(pairs);
            const smallWord = AU_COIN_WORDS[(AU_COIN_CENTS as readonly number[]).indexOf(small)];
            const bigWord = AU_COIN_WORDS[(AU_COIN_CENTS as readonly number[]).indexOf(big)];
            return {
                prompt: `How many ${smallWord} coins are the same as one ${bigWord} coin?`,
                answer: `${big / small}`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const moneySpec: WorksheetSpec = {
    id: 'money',
    label: 'Coins & Money',
    icon: '$',
    perPage: 12,
    // Money questions are worded — prints single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('money'),
    scope: (grade: GradeConfig) => `coins up to $${Math.max(1, Math.round(grade.caps.coinCap / 100))}`,
    generate: generateMoney
};

// The plugin: a function the dashboard calls with its framework bundle.
export function MoneyWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(moneySpec);
}
