// ─────────────────────────────────────────────────────────────────────────────
// MULTIPLICATION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `MultiplicationWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Multiplication", glyph "×") and which grades offer
//     it (times tables start at Year 2 — grade.available gates the rail);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Multiplication worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Multiplication / times tables: `a × b = __` with both operands in
// [1, multCap]. Grade 2 introduces times tables (to 10), so with its cap
// every product stays <= multCap * multCap (100) — right-sized for the grade.
function generateMultiplication(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    // A grade that doesn't offer multiplication passes multCap 0; the
    // generator is unreachable for them (buildDocument checks grade.available
    // through the spec's offered() first).
    const cap = Math.max(1, caps.multCap);
    for (let i = 0; i < count; i++) {
        const a = rng.int(1, cap);
        const b = rng.int(1, cap);
        out.push({ prompt: `${a} × ${b} = __`, answer: `${a * b}` });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const multiplicationSpec: WorksheetSpec = {
    id: 'mult',
    label: 'Multiplication',
    icon: '×',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('mult'),
    scope: (grade: GradeConfig) => `times tables to ${grade.caps.multCap}`,
    generate: generateMultiplication
};

// The plugin: a function the dashboard calls with its framework bundle.
export function MultiplicationWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(multiplicationSpec);
}
