// ─────────────────────────────────────────────────────────────────────────────
// MULTIPLICATION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `MultiplicationWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Multiplication", glyph "×") and which grades offer
//     it (times tables start at Year 2 — grade.available gates the rail);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Multiplication worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Multiplication / times tables, THREE procedural forms over the same fact
// space (a × b with both operands in [1, multCap]):
//   0. product unknown:      "7 × 8 = __"        (the classic recall form)
//   1. first factor unknown: "__ × 8 = 56"       (missing-factor, V9
//      AC9M2N05 relational thinking)
//   2. second factor unknown: "7 × __ = 56"
// Grade 2 introduces times tables (to 10), so with its cap every product
// stays <= multCap * multCap (100) — right-sized for the grade.
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so each of the 100 facts prints once per
// FORM before the space cycles — a 100-page document still spreads the
// three forms evenly (the old free-draw loop could print "7 × 8 = __"
// twice on one page).
function generateMultiplication(rng: Rng, caps: Caps, count: number): RawProblem[] {
    // A grade that doesn't offer multiplication passes multCap 0; the
    // generator is unreachable for them (buildDocument checks grade.available
    // through the spec's offered() first).
    const cap = Math.max(1, caps.multCap);
    return sampleUnique(
        count,
        () => {
            const a = rng.int(1, cap);
            const b = rng.int(1, cap);
            const form = rng.int(0, 2);
            if (form === 0) {
                return { prompt: `${a} × ${b} = __`, answer: `${a * b}` };
            }
            if (form === 1) {
                return { prompt: `__ × ${b} = ${a * b}`, answer: `${a}` };
            }
            return { prompt: `${a} × __ = ${a * b}`, answer: `${b}` };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const multiplicationSpec: WorksheetSpec = {
    id: 'mult',
    label: 'Multiplication',
    icon: '×',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('mult'),
    scope: (grade: GradeConfig) => `times tables to ${grade.caps.multCap}`,
    generate: generateMultiplication
};

// The plugin: a function the dashboard calls with its framework bundle.
export function MultiplicationWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(multiplicationSpec);
}
