// ─────────────────────────────────────────────────────────────────────────────
// NUMBER BONDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `NumberBondsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Number Bonds", glyph "∨") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// DEPTH-FIRST SHEET (quality over quantity): SIX bond tasks per A4 page
// (single column — each row carries its part-part-whole diagram AND a
// multi-part prompt with real writing space), instead of the old 16 single-
// blank bonds. The tasks now span the whole part-part-whole idea: fill BOTH
// parts of a given whole from the diagram, a bond with BOTH related
// subtractions, a story whose bond sentence the student writes out, a
// missing-WHOLE item (the hardest bond direction), and — Year 2 — the
// make-ten bridge for crossing ten.
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Number Bonds worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Number bonds / part-part-whole (V9 AC9M1N02: "to 10" in Y1; Y2 bridges
// through 10 and 20). The total is 10 when bondCap < 20, otherwise 10 or 20.
//
// The task families. Every printed task carries 2–3 blanks whose answers are
// recorded in order in `answer` (comma separated — RawProblem allows it), so
// the answer key covers EVERY requested part:
//   bothParts    — diagram with BOTH part circles blank: the student splits
//                  the whole into the pair this sheet generated (the figure
//                  shows the whole; the parts are the private answer)
//   relatedSub   — "p + __ = T and T - p = __" (the same bond, two faces)
//   story        — a grown-part story; the missing part AND the bond
//                  sentence "__ + __ = T" are written
//   missingWhole — "__ - p = q and q + p = __" (the whole is the unknown —
//                  no diagram, the whole is not printed anywhere)
//   makeTen      — Year 2 only: "9 + 6 = 10 + __ = __" — the crossing-ten
//                  bridge built directly on bonds of 10
//
// NON-REPEATING SAMPLING: the family is dealt from a deck (every family
// appears before any repeats) and the whole question passes through
// sampleUnique keyed on the printed prompt, so each bond prints once per
// FORM before the space cycles.
function generateBonds(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const totals = caps.bondCap >= 20 ? [10, 20] : [Math.max(5, caps.bondCap)];
    // Year 2 (bondCap >= 20) additionally bridges through ten; the pair
    // grades keep the four core families.
    const forms = caps.bondCap >= 20
        ? (['bothParts', 'relatedSub', 'story', 'missingWhole', 'makeTen'] as const)
        : (['bothParts', 'relatedSub', 'story', 'missingWhole'] as const);
    const formDeck = createDeck(rng, forms);
    return sampleUnique(
        count,
        () => {
            const form = formDeck.take();
            const total = rng.pick(totals);
            // Both parts of a bond are NON-ZERO (1..total-1) — a "10 + __ = 10"
            // item teaches nothing and would confuse the part-part-whole idea.
            const part = rng.int(1, total - 1);
            const other = total - part;
            if (form === 'bothParts') {
                // SPLIT THE WHOLE: the diagram prints the whole with BOTH
                // part circles blank (framework/BondDiagram.tsx leaves null
                // parts empty — the missing answers are never drawn).
                return {
                    prompt: `The whole is ${total}. Write its two parts: __ and __`,
                    answer: `${part}, ${other}`,
                    bond: { whole: total, left: null, right: null }
                };
            }
            if (form === 'relatedSub') {
                // TWO FACES OF ONE BOND: the addition blank and the matching
                // subtraction are the SAME missing part — the student sees
                // the bond and the subtraction are one idea.
                return {
                    prompt: `${part} + __ = ${total} and ${total} - ${part} = __`,
                    answer: `${other}, ${other}`,
                    bond: { whole: total, left: part, right: null }
                };
            }
            if (form === 'story') {
                // STORY + SENTENCE: the missing part is found, then the
                // whole bond is written out as an addition sentence.
                return {
                    prompt: `A tower of ${total} cubes has ${part} showing. The hidden part is __; the bond is __ + __ = ${total}`,
                    answer: `${other}, ${part}, ${other}`,
                    bond: { whole: total, left: part, right: null }
                };
            }
            if (form === 'missingWhole') {
                // MISSING WHOLE: the hardest bond direction — the difference
                // and one part are given, the whole must be rebuilt, and the
                // partner addition confirms it. No diagram: the whole is the
                // answer and must never be printed.
                return {
                    prompt: `__ - ${part} = ${other} and ${other} + ${part} = __`,
                    answer: `${total}, ${total}`
                };
            }
            // MAKE TEN (Year 2): split the SECOND addend so 9..(x) makes 10
            // first — "8 + 7 = 10 + 5 = 15". x is 6..9 so the ten-bond is
            // worth using, and y is drawn large enough that the leftover is
            // a positive part of 10 (never 0).
            const x = rng.int(6, 9);
            const y = rng.int(11 - x, Math.max(11 - x, 20 - x)); // leftover >= 1, sum <= 20
            return {
                prompt: `${x} + ${y} = 10 + __ = __`,
                answer: `${y - (10 - x)}, ${x + y}`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const bondsSpec: WorksheetSpec = {
    id: 'bonds',
    label: 'Number Bonds',
    icon: '∨',
    // FIVE bond tasks per A4: every row carries a part-part-whole diagram
    // (framework/BondDiagram.tsx) AND a multi-part prompt, printed in ONE
    // column so each task owns a generous band of the sheet — the diagrams
    // stay hand-sizeable and the writing space is real.
    // LAYOUT CAPACITY (T3M3): worst row = two prompt lines (2×21.6px) +
    // BondDiagram block (6+85px) = 134.2px; at 6/page the 1fr row is 132.4px
    // (overflow), at 5/page 163.6px (margin 29.4). layout-capacity.test.ts.
    perPage: 5,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('bonds'),
    scope: (grade: GradeConfig) =>
        grade.caps.bondCap >= 20 ? 'bonds to 10 & 20' : `bonds to ${Math.max(5, grade.caps.bondCap)}`,
    generate: generateBonds
};

// The plugin: a function the dashboard calls with its framework bundle.
export function NumberBondsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(bondsSpec);
}
