// ─────────────────────────────────────────────────────────────────────────────
// NUMBER BONDS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `NumberBondsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Number Bonds", glyph "∨") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Number Bonds worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Number bonds / part-part-whole (V9 AC9M1N02: "to 10" in Y1; Y2 bridges
// through 10 and 20). The total is 10 when bondCap < 20, otherwise 10 or 20.
function generateBonds(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const totals = caps.bondCap >= 20 ? [10, 20] : [Math.max(5, caps.bondCap)];
    for (let i = 0; i < count; i++) {
        const total = rng.pick(totals);
        // Both parts of a bond are NON-ZERO (1..total-1) — a "10 + __ = 10"
        // item teaches nothing and would confuse the part-part-whole idea.
        const a = rng.int(1, total - 1);
        const missing = total - a; // the hidden part, 1..total-1
        const r = rng.next();
        const prompt =
            r < 0.4 ? `${a} + __ = ${total}` : r < 0.7 ? `__ + ${a} = ${total}` : `__ and ${a} make ${total}`;
        out.push({ prompt, answer: `${missing}` });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const bondsSpec: WorksheetSpec = {
    id: 'bonds',
    label: 'Number Bonds',
    icon: '∨',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('bonds'),
    scope: (grade: GradeConfig) =>
        grade.caps.bondCap >= 20 ? 'bonds to 10 & 20' : `bonds to ${Math.max(5, grade.caps.bondCap)}`,
    generate: generateBonds
};

// The plugin: a function the dashboard calls with its framework bundle.
export function NumberBondsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(bondsSpec);
}
