// ─────────────────────────────────────────────────────────────────────────────
// PATTERNS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PatternsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Patterns", glyph "↻") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// DEPTH-FIRST SHEET (quality over quantity): EIGHT connected tasks per A4
// page (single column — every prompt is a multi-part line with real writing
// space), instead of the old 16 single-blank rows. Patterns are now DEEPER:
// runs with TWO blanks, runs whose RULE the student states ("the rule is add
// __"), word cycles continued TWO places, cycles whose repeat length is
// named, and a count-on run offered as a claim to check (Correct/Wrong) —
// the V9 AC9M2A01 missing-element + rule-describing asks.
//
// Fully self-contained: the repeating-pattern word pools live IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Patterns worksheet
// without affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Word pools for repeating-pattern items: each column is one pool; the
// generator deals 3 distinct words from it (through a deck) to form an
// A-B or A-B-C cycle (V9 AC9M1A01/AC9M2A01: repeating + constant-step
// patterns with missing elements). Words are printed as TEXT — the sheet
// never relies on pictorial glyphs the printer may not carry.
const PATTERN_POOLS = [
    ['red', 'blue', 'green', 'yellow', 'pink', 'black', 'white', 'orange'],
    ['circle', 'square', 'triangle', 'oval', 'star', 'heart', 'diamond', 'cross'],
    ['cat', 'dog', 'fish', 'bird', 'frog', 'duck', 'pig', 'bee']
] as const;

// The task families. Every printed task carries 2 blanks (or one word blank)
// whose answers are recorded in order in `answer` (comma separated —
// RawProblem allows it), so the answer key covers EVERY requested part:
//   twoBlanks — "s, s+st, __, s+3st, __"        (two gaps, one count-on run)
//   rule      — "s, s+st, s+2st, s+3st, __; the rule is add __" (extend AND
//               describe — the reasoning ask)
//   extend    — "s, s+st, s+2st, __, __"        (two terms beyond the shown)
//   wordTwo   — a word cycle with the NEXT TWO terms blank
//   wordRule  — a word cycle, next term + "repeats every __ shapes"
//   verifyRun — "Counting on by st from s gives a, b, c, d. __" — the run is
//               printed with a possibly WRONG last term: Correct/Wrong claim
//
// NON-REPEATING SAMPLING: pools and steps are dealt from decks and every
// question passes through sampleUnique keyed on the printed prompt, so the
// same cycle with a different start/step/blank position is a fresh question.
const PATTERNS_FORMS = ['twoBlanks', 'rule', 'extend', 'wordTwo', 'wordRule', 'verifyRun'] as const;

function generatePatterns(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const steps = caps.patSet.length ? [...caps.patSet].sort((a, b) => a - b) : [1, 2, 5];
    const fallback = steps[0];
    const stepDeck = createDeck(rng, steps);
    const poolDeck = createDeck(rng, PATTERN_POOLS);
    const formDeck = createDeck(rng, PATTERNS_FORMS);
    // Deal a step whose 4-jump span still fits inside skipCap (the numeric
    // runs all reach start + 4 x step at most).
    const drawStep = () => {
        let step = stepDeck.take();
        if (step * 4 > caps.skipCap) step = fallback;
        return step;
    };
    // Deal 3 DISTINCT words from a pool (a shuffled slice of 3 — distinct by
    // construction, order is the randomness) and wrap them as an A-B or
    // A-B-C cycle.
    const drawCycle = (): string[] => {
        const pool = [...poolDeck.take()];
        const picked: string[] = [];
        while (picked.length < 3) {
            const w = pool.splice(rng.int(0, pool.length - 1), 1)[0];
            picked.push(w);
        }
        const [w1, w2, w3] = picked as [string, string, string];
        return rng.next() < 0.5 ? [w1, w2] : [w1, w2, w3];
    };
    return sampleUnique(
        count,
        () => {
            const form = formDeck.take();
            if (form === 'twoBlanks') {
                // Forward run with gaps at positions 2 and 4 (0-based).
                const step = drawStep();
                const start = rng.int(0, Math.max(0, caps.skipCap - 4 * step));
                return {
                    prompt: `${start}, ${start + step}, __, ${start + 3 * step}, __`,
                    answer: `${start + 2 * step}, ${start + 4 * step}`
                };
            }
            if (form === 'rule') {
                // EXTEND + DESCRIBE: four shown terms pin the step exactly,
                // so the "rule is add __" blank is unambiguous.
                const step = drawStep();
                const start = rng.int(0, Math.max(0, caps.skipCap - 4 * step));
                return {
                    prompt: `${start}, ${start + step}, ${start + 2 * step}, ${start + 3 * step}, __; the rule is add __`,
                    answer: `${start + 4 * step}, ${step}`
                };
            }
            if (form === 'extend') {
                // TWO TERMS BEYOND: the run continues twice more.
                const step = drawStep();
                const start = rng.int(0, Math.max(0, caps.skipCap - 4 * step));
                return {
                    prompt: `${start}, ${start + step}, ${start + 2 * step}, __, __`,
                    answer: `${start + 3 * step}, ${start + 4 * step}`
                };
            }
            if (form === 'wordTwo') {
                // WORD CYCLE, NEXT TWO BLANK: four terms shown (two full
                // cycles for A-B, one and a bit for A-B-C), then the student
                // continues the cycle twice.
                const cycle = drawCycle();
                const shown = Array.from({ length: 4 }, (_, k) => cycle[k % cycle.length]);
                const answers = [cycle[4 % cycle.length], cycle[5 % cycle.length]];
                return { prompt: `${shown.join(', ')}, __, __`, answer: answers.join(', ') };
            }
            if (form === 'wordRule') {
                // WORD CYCLE + REPEAT LENGTH: continue once, then state how
                // many shapes the cycle is built from.
                const cycle = drawCycle();
                const shown = Array.from({ length: 5 }, (_, k) => cycle[k % cycle.length]);
                return {
                    prompt: `${shown.join(', ')}, __; the pattern repeats every __ shapes`,
                    answer: `${cycle[5 % cycle.length]}, ${cycle.length}`
                };
            }
            // VERIFY THE RUN: the first three terms are always a true count-
            // on-by-step run; the FOURTH is right ~2/3 of the time and off
            // by one otherwise — the student checks, not just continues.
            const step = drawStep();
            const start = rng.int(0, Math.max(0, caps.skipCap - 3 * step));
            const correct = start + 3 * step;
            const shown4 = rng.next() < 2 / 3 ? correct : correct + (rng.next() < 0.5 ? 1 : -1);
            return {
                prompt: `Counting on by ${step} from ${start} gives ${start}, ${start + step}, ${start + 2 * step}, ${shown4}. __ (Correct or Wrong)`,
                answer: shown4 === correct ? 'Correct' : 'Wrong',
                wideBlanks: true
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const patternsSpec: WorksheetSpec = {
    id: 'patterns',
    label: 'Patterns',
    icon: '↻',
    // Eight connected multi-part tasks per A4, printed in ONE column so every
    // run has the full page width and the rows stretch to fill the sheet —
    // fewer questions, far more thinking and writing space each.
    perPage: 8,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('patterns'),
    scope: (grade: GradeConfig) => `steps of ${[...grade.caps.patSet].sort((a, b) => a - b).join(', ')}`,
    generate: generatePatterns
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PatternsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(patternsSpec);
}
