// ─────────────────────────────────────────────────────────────────────────────
// PLACE VALUE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PlaceValueWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Place Value", glyph "⊞") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Place Value worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Place value (V9 AC9M1N02/AC9M2N02 partitions into tens & ones; Y1 range is
// at most 20, Y2 up to pvCap=99). Four forms: decompose a number, compose a
// number from tens/ones, "how many tens in N", "how many ones in N".
function generatePlaceValue(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const cap = Math.max(10, caps.pvCap);
    // "1 ten" / "1 one" (singular) vs "4 tens" / "5 ones".
    const words = (t: number) => (t === 1 ? 'ten' : 'tens');
    const onesWord = (o: number) => (o === 1 ? 'one' : 'ones');
    for (let i = 0; i < count; i++) {
        const r = rng.next();
        if (r < 0.35) {
            // Decompose: N = t tens and o ones.
            const n = rng.int(10, cap);
            const t = Math.floor(n / 10);
            out.push({ prompt: `How many tens and ones make ${n}?`, answer: `${t} ${words(t)} and ${n % 10} ${onesWord(n % 10)}` });
        } else if (r < 0.6) {
            // Compose: "what number is t tens and o ones?" The ones must be a
            // DIGIT (0..9) and the total must stay within the cap, so at the
            // top tens row only trailing zeros are allowed.
            const t = rng.int(1, Math.floor(cap / 10));
            const o = rng.int(0, Math.min(9, cap - t * 10));
            out.push({ prompt: `What number is ${t} ${words(t)} and ${o} ${onesWord(o)}?`, answer: `${t * 10 + o}` });
        } else if (r < 0.8) {
            // Tens digit of N.
            const n = rng.int(10, cap);
            out.push({ prompt: `How many tens are in ${n}?`, answer: `${Math.floor(n / 10)}` });
        } else {
            // Ones digit of N (legitimately 0 for round tens like 20).
            const n = rng.int(10, cap);
            out.push({ prompt: `How many ones are in ${n}?`, answer: `${n % 10}` });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const placeValueSpec: WorksheetSpec = {
    id: 'placevalue',
    label: 'Place Value',
    icon: '⊞',
    perPage: 16,
    offered: (grade: GradeConfig) => grade.available.includes('placevalue'),
    scope: (grade: GradeConfig) => `tens & ones to ${Math.max(10, grade.caps.pvCap)}`,
    generate: generatePlaceValue
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PlaceValueWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(placeValueSpec);
}
