// ─────────────────────────────────────────────────────────────────────────────
// PLACE VALUE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PlaceValueWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Place Value", glyph "⊞") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Place Value worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Place value (V9 AC9M1N02/AC9M2N02 partitions into tens & ones; Y1 range is
// at most 20, Y2 up to pvCap=99). SIX forms over the (N, tens, ones) fact
// space — the number range is small, so the form variants are what keep a
// long document fresh:
//   0. decompose:   "How many tens and ones make N?"
//   1. compose:     "What number is t tens and o ones?"
//   2. tens ask:    "How many tens are in N?"
//   3. ones ask:    "How many ones are in N?"
//   4. digit ask:   "What is the tens digit of N?"   (the DIGIT, not the
//                   quantity — a distinct Y2 skill)
//   5. edit ask:    "N is __ tens and __ ones" (both blanks; Y2 two-digit
//                   partition written as one line — the answer lists both)
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so each number prints once per FORM before
// the space cycles.
function generatePlaceValue(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(10, caps.pvCap);
    // "1 ten" / "1 one" (singular) vs "4 tens" / "5 ones".
    const words = (t: number) => (t === 1 ? 'ten' : 'tens');
    const onesWord = (o: number) => (o === 1 ? 'one' : 'ones');
    return sampleUnique(
        count,
        () => {
            const form = rng.int(0, 5);
            if (form === 0) {
                // Decompose: N = t tens and o ones.
                const n = rng.int(10, cap);
                const t = Math.floor(n / 10);
                return { prompt: `How many tens and ones make ${n}?`, answer: `${t} ${words(t)} and ${n % 10} ${onesWord(n % 10)}` };
            }
            if (form === 1) {
                // Compose: "what number is t tens and o ones?" The ones must be a
                // DIGIT (0..9) and the total must stay within the cap, so at the
                // top tens row only trailing zeros are allowed.
                const t = rng.int(1, Math.floor(cap / 10));
                const o = rng.int(0, Math.min(9, cap - t * 10));
                return { prompt: `What number is ${t} ${words(t)} and ${o} ${onesWord(o)}?`, answer: `${t * 10 + o}` };
            }
            if (form === 2) {
                // Tens quantity of N.
                const n = rng.int(10, cap);
                return { prompt: `How many tens are in ${n}?`, answer: `${Math.floor(n / 10)}` };
            }
            if (form === 3) {
                // Ones quantity of N (legitimately 0 for round tens like 20).
                const n = rng.int(10, cap);
                return { prompt: `How many ones are in ${n}?`, answer: `${n % 10}` };
            }
            if (form === 4) {
                // Tens DIGIT of N (the digit, not the quantity).
                const n = rng.int(10, cap);
                return { prompt: `What is the tens digit of ${n}?`, answer: `${Math.floor(n / 10)}` };
            }
            // Both-blanks partition: the answer names both parts.
            const n = rng.int(10, cap);
            const t = Math.floor(n / 10);
            return { prompt: `${n} is __ tens and __ ones`, answer: `${t} tens and ${n % 10} ones` };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const placeValueSpec: WorksheetSpec = {
    id: 'placevalue',
    label: 'Place Value',
    icon: '⊞',
    perPage: 16,
    offered: (grade: GradeConfig) => grade.available.includes('placevalue'),
    scope: (grade: GradeConfig) => `tens & ones to ${Math.max(10, grade.caps.pvCap)}`,
    generate: generatePlaceValue
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PlaceValueWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(placeValueSpec);
}
