// ─────────────────────────────────────────────────────────────────────────────
// PLACE VALUE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `PlaceValueWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Place Value", glyph "⊞") and which grades offer it
//     (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Place Value worksheet without affecting the framework or any
// other plugin.
//
// DEPTH DESIGN (quality over quantity): eight CONNECTED items per page
// instead of sixteen isolated one-blank recalls. Each item anchors one number
// (or one pair of numbers) and asks two linked questions — (a)/(b) print on
// their own lines (PrintableSheet's ProblemText is white-space: pre-wrap)
// with their own "__" blank, and the answer string lists BOTH results in
// order. The seven forms over the (N, tens, ones) fact space:
//   tensOnesOf   — read the partition of N apart: how many tens, leftover ones
//   composeMore  — build N from t tens + o ones, then step it by 1 (Y1) / 10 (Y2)
//   decade       — 1 more than 9/19/29… crosses the decade, then count its tens
//   compare      — which of two numbers is greater AND by how much
//   riddle       — reverse construction: ones digit GIVEN RELATIVE to tens
//   cards (Y2)   — greatest/smallest 2-digit number from two digit cards
//   tenMore (Y2) — 10 more AND 10 less than N (inverse pair on one anchor)
// Year 1 stays inside tens & ones to 20; Year 2 widens to pvCap = 99.
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so each number prints once per FORM before
// the space cycles.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

function generatePlaceValue(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(10, caps.pvCap);
    // "1 ten" / "1 one" (singular) vs "4 tens" / "5 ones".
    const words = (t: number) => (t === 1 ? 'ten' : 'tens');
    const onesWord = (o: number) => (o === 1 ? 'one' : 'ones');
    // Numbers one below a decade boundary (9, 19, 29, …) inside the grade's
    // range — the crossing points that make "1 more" real place-value work.
    const decadeNums: number[] = [];
    for (let n = 9; n <= cap - 1; n += 10) decadeNums.push(n);
    // The Y2-only forms need the wider 10..99 space; Year 1 (cap 20) would
    // make them degenerate, so they join the pool only when cap is wide.
    const wide = cap >= 50;
    // Largest legal riddle tens digit: n = 11t + d ≤ cap needs 11t + 1 ≤ cap.
    const riddleTMax = Math.floor((cap - 1) / 11);
    return sampleUnique(
        count,
        () => {
            const kinds = ['tensOnesOf', 'composeMore', 'decade', 'compare', ...(riddleTMax >= 1 ? ['riddle'] : []), ...(wide ? ['cards', 'tenMore'] : [])];
            const form = rng.pick(kinds);
            if (form === 'tensOnesOf') {
                // The partition read APART — tens first, leftover ones second.
                const n = rng.int(10, cap);
                const t = Math.floor(n / 10);
                return {
                    prompt:
                        `Look at the number ${n}.\n` +
                        `(a) How many tens are in ${n}? __\n` +
                        `(b) How many ones are left over? __`,
                    answer: `${t} ${words(t)}, ${n % 10} ${onesWord(n % 10)}`
                };
            }
            if (form === 'composeMore') {
                // Compose, then step: Y1 steps by 1 (within-20 scope), Y2 by
                // 10 (the "same ones digit, one more ten" insight). n+step ≤
                // cap is enforced by the draw, so the answer never escapes
                // the grade's number range.
                const step = wide ? 10 : 1;
                const t = rng.int(1, Math.floor((cap - step) / 10));
                const o = rng.int(0, Math.min(9, cap - step - t * 10));
                const n = t * 10 + o;
                return {
                    prompt:
                        `Write the number: ${t} ${words(t)} and ${o} ${onesWord(o)}.\n` +
                        `(a) What number is it? __\n` +
                        `(b) What is ${step} more than that number? __`,
                    answer: `${n}, ${n + step}`
                };
            }
            if (form === 'decade') {
                // Crossing the decade: 19 + 1 = 20, then COUNT the new tens —
                // the exchange itself is the question.
                const n = rng.pick(decadeNums);
                const next = n + 1;
                return {
                    prompt:
                        `(a) What is 1 more than ${n}? __\n` +
                        `(b) How many tens are in your answer? __`,
                    answer: `${next}, ${Math.floor(next / 10)}`
                };
            }
            if (form === 'compare') {
                // Comparison AND the size of the gap (digit-place reasoning
                // made visible by the difference).
                const a = rng.int(10, cap);
                let b = rng.int(10, cap);
                while (b === a) b = rng.int(10, cap);
                const hi = Math.max(a, b);
                const lo = Math.min(a, b);
                return {
                    prompt:
                        `(a) Which is greater, ${a} or ${b}? __\n` +
                        `(b) How many more? __`,
                    answer: `${hi}, ${hi - lo}`
                };
            }
            if (form === 'riddle') {
                // Reverse construction: the ones digit is GIVEN RELATIVE to
                // the tens digit; (a) finds it, (b) assembles the number.
                // n = 11t + d, so d ≤ min(9 - t, cap - 11t) keeps the ones
                // digit a digit AND the number inside the grade's range.
                const t = rng.int(1, riddleTMax);
                const d = rng.int(1, Math.min(9 - t, cap - 11 * t));
                const ones = t + d;
                const n = t * 10 + ones;
                return {
                    prompt:
                        `I am thinking of a 2-digit number. Its tens digit is ${t}. Its ones digit is ${d} more than its tens digit.\n` +
                        `(a) What is my ones digit? __\n` +
                        `(b) What is my number? __`,
                    answer: `${ones}, ${n}`
                };
            }
            if (form === 'cards') {
                // Year 2: the two orders of the SAME digit cards bracket the
                // range — greatest needs the bigger digit in the tens place.
                const x = rng.int(1, 9);
                let y = rng.int(1, 9);
                while (y === x) y = rng.int(1, 9);
                const hi = Math.max(x, y);
                const lo = Math.min(x, y);
                return {
                    prompt:
                        `You have two digit cards: ${x} and ${y}.\n` +
                        `(a) What is the greatest 2-digit number you can make? __\n` +
                        `(b) What is the smallest 2-digit number you can make? __`,
                    answer: `${hi * 10 + lo}, ${lo * 10 + hi}`
                };
            }
            // 'tenMore' (Year 2): the inverse pair on one anchor — 10 more
            // AND 10 less keep the ones digit unchanged.
            const n = rng.int(20, cap - 10);
            return {
                prompt:
                    `Think about the number ${n}.\n` +
                    `(a) What is 10 more than ${n}? __\n` +
                    `(b) What is 10 less than ${n}? __`,
                answer: `${n + 10}, ${n - 10}`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const placeValueSpec: WorksheetSpec = {
    id: 'placevalue',
    label: 'Place Value',
    icon: '⊞',
    // FOUR connected two-part items instead of sixteen one-blank recalls.
    // LAYOUT CAPACITY (T3M3): worst row = the "I am thinking of a 2-digit
    // number" story, five wrapped 22px prompt lines (5×33px) = 165.0px;
    // two-column rows would clip it (297.0px worst), so the sheet prints
    // single-column at 4/page (row 210.5px, margin 45.5).
    // See plugins/layout-capacity.test.ts for the model.
    perPage: 4,
    // Multi-part stories wrap badly in 297px columns — print single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('placevalue'),
    scope: (grade: GradeConfig) => `tens & ones to ${Math.max(10, grade.caps.pvCap)}`,
    generate: generatePlaceValue
};

// The plugin: a function the dashboard calls with its framework bundle.
export function PlaceValueWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(placeValueSpec);
}
