// ─────────────────────────────────────────────────────────────────────────────
// SHAPES & ATTRIBUTES WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `ShapesWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Shapes & Attributes', glyph '△') and which grades
//     offer it (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: the shape catalogue lives IN this plugin (duplicated
// deliberately — plugins never import from each other). Deleting this file
// and its line in plugins/index.ts removes the Shapes worksheet without
// affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { sampleUnique } from '../framework';

// Shape catalogue for the shapes generator (V8-aligned 2-D + 3-D set: V9 keeps
// 3-D features for Year 3, but the app's Y2 already teaches V8-era content).
// `sides` counts STRAIGHT sides only (0 for curved-only shapes); `corners`
// is 2-D vertices; `flatFaces` is 3-D flat faces (0 for a sphere).
type ShapeDef = {
    name: string;
    sides: number;
    corners: number;
    flatFaces: number;
    curved: boolean;
    kind: '2d' | '3d';
};
const SHAPES: ShapeDef[] = [
    { name: 'circle', sides: 0, corners: 0, flatFaces: 0, curved: true, kind: '2d' },
    { name: 'oval', sides: 0, corners: 0, flatFaces: 0, curved: true, kind: '2d' },
    { name: 'triangle', sides: 3, corners: 3, flatFaces: 0, curved: false, kind: '2d' },
    { name: 'square', sides: 4, corners: 4, flatFaces: 0, curved: false, kind: '2d' },
    { name: 'rectangle', sides: 4, corners: 4, flatFaces: 0, curved: false, kind: '2d' },
    { name: 'hexagon', sides: 6, corners: 6, flatFaces: 0, curved: false, kind: '2d' },
    { name: 'cube', sides: 0, corners: 0, flatFaces: 6, curved: false, kind: '3d' },
    { name: 'prism', sides: 0, corners: 0, flatFaces: 6, curved: false, kind: '3d' },
    { name: 'pyramid', sides: 0, corners: 0, flatFaces: 4, curved: false, kind: '3d' },
    { name: 'cylinder', sides: 0, corners: 0, flatFaces: 2, curved: true, kind: '3d' },
    { name: 'cone', sides: 0, corners: 0, flatFaces: 1, curved: true, kind: '3d' },
    { name: 'sphere', sides: 0, corners: 0, flatFaces: 0, curved: true, kind: '3d' }
];
// Filter the catalogue down to the shapes the grade offers (names come from
// the grade's shapeSet); a grade with an empty set falls back to the FULL set
// so the generator can never run out of material.
function shapesFor(caps: Caps): ShapeDef[] {
    const avail = SHAPES.filter((s) => caps.shapeSet.includes(s.name));
    return avail.length >= 3 ? avail : SHAPES;
}
// "a"/"an" article for shape names (a circle, an oval).
function shapeArticle(name: string): string {
    return /^[aeiou]/i.test(name) ? 'an' : 'a';
}

// 2-D & 3-D shape recognition + attributes (V8 ACMMG159/174-175 era; V9 keeps
// the 2-D attribute questions for Y2 and moves 3-D features to Y3). Each
// question variant must pick from shapes the grade actually offers (shapeSet);
// if a variant's candidate pool is empty the generator degrades to the next
// simpler variant so Prep-sized shape sets still produce valid items.
//
// NON-REPEATING SAMPLING: the whole question passes through sampleUnique
// keyed on the printed prompt, so the same MC option list never prints twice
// in a row and the finite shape-bank space is spread evenly before repeats.
function generateShapes(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const shapes = shapesFor(caps);
    const twoD = shapes.filter((s) => s.kind === '2d');
    const threeD = shapes.filter((s) => s.kind === '3d');
    return sampleUnique(
        count,
        () => {
            const r = rng.next();
            if (r < 0.25) {
                // "How many (straight) sides..." — only shapes that have them.
                // The figure draws the exact 2-D outline (framework/ShapeFigure.tsx);
                // the side count stays the private answer.
                const pool = twoD.filter((s) => s.sides > 0);
                const s = rng.pick(pool.length ? pool : twoD);
                return {
                    prompt: `How many sides does ${shapeArticle(s.name)} ${s.name} have?`,
                    answer: `${s.sides}`,
                    shapes: [{ name: s.name, kind: '2d' }]
                };
            }
            if (r < 0.45) {
                // "How many corners..." — circles/ovals answer 0 (curved side).
                const s = rng.pick(twoD);
                return {
                    prompt: `How many corners does ${shapeArticle(s.name)} ${s.name} have?`,
                    answer: `${s.corners}`,
                    shapes: [{ name: s.name, kind: '2d' }]
                };
            }
            if (r < 0.65 && threeD.length >= 3) {
                // "How many flat faces..." — 3-D objects only. The figure draws the
                // solid's line drawing; the face count stays the private answer.
                const s = rng.pick(threeD);
                return {
                    prompt: `How many flat faces does ${shapeArticle(s.name)} ${s.name} have?`,
                    answer: `${s.flatFaces}`,
                    shapes: [{ name: s.name, kind: '3d' }]
                };
            }
            if (r < 0.8) {
                // Multiple-choice on 2-D corners: the answer must be UNIQUE among
                // the shown options, so distractors share no corner count with it.
                let answer = rng.pick(twoD);
                let distractors = twoD.filter((s) => s.name !== answer.name && s.corners !== answer.corners);
                if (distractors.length < 2) {
                    // Deeper ambiguity (e.g. only circles+ovals offered) — fall
                    // back to a plain "how many corners" line instead.
                    answer = rng.pick(twoD);
                    return {
                        prompt: `How many corners does ${shapeArticle(answer.name)} ${answer.name} have?`,
                        answer: `${answer.corners}`,
                        shapes: [{ name: answer.name, kind: '2d' }]
                    };
                }
                // Two distractors with different corner counts; the correct
                // shape sits at a random position in the printed list.
                const d1 = rng.pick(distractors);
                const d2 = rng.pick(distractors.filter((s) => s.name !== d1.name));
                const order = [answer, d1, d2];
                const at = rng.int(0, 2);
                const shown = [order[at], ...order.filter((s) => s !== order[at])];
                return {
                    prompt: `Which 2-D shape has ${answer.corners} corners? (${shown.map((s) => s.name).join(', ')})`,
                    answer: answer.name,
                    // Drawn in the prompt's option order, labelled under each
                    // outline (the labels keep the question unambiguous).
                    shapes: shown.map((s) => ({ name: s.name, kind: '2d' as const }))
                };
            }
            // 3-D "only flat faces" identification — shapes with NO curved surface (cube
            // / prism / pyramid); cones & cylinders have a curved side and a
            // sphere none at all, so flatFaces>0 is the WRONG filter.
            const allFlat = threeD.filter((s) => !s.curved);
            if (threeD.length >= 3 && allFlat.length >= 1) {
                const answer = rng.pick(allFlat);
                const others = threeD.filter((s) => s.name !== answer.name);
                // Distractors come from the CURVED-surface solids (cylinder /
                // cone / sphere) so the asked object is the UNIQUE all-flat
                // choice: Year 2's cube, prism AND pyramid are all all-flat,
                // so drawing distractors from the whole set would leave the
                // question with several correct candidates (T3 audit). A set
                // with fewer than two curved 3-D shapes falls back to the
                // original pool (the variant's own gate keeps it usable).
                const curved = threeD.filter((s) => s.curved);
                const pool = curved.length >= 2 ? curved : others;
                const d1 = rng.pick(pool);
                const d2 = rng.pick(pool.filter((s) => s.name !== d1.name));
                return {
                    prompt: `Which of these 3-D objects has only flat faces? (${[answer, d1, d2].map((s) => s.name).join(', ')})`,
                    answer: answer.name,
                    // Three labelled 3-D line drawings, in the prompt's order.
                    shapes: [
                        { name: answer.name, kind: '3d' as const },
                        { name: d1.name, kind: '3d' as const },
                        { name: d2.name, kind: '3d' as const }
                    ]
                };
            }
            const curved = twoD.filter((s) => s.curved);
            const answer = rng.pick(curved.length ? curved : twoD);
            return {
                prompt: `Does ${shapeArticle(answer.name)} ${answer.name} have a curved side?`,
                answer: answer.curved ? 'Yes' : 'No',
                shapes: [{ name: answer.name, kind: '2d' as const }]
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const shapesSpec: WorksheetSpec = {
    id: 'shapes',
    label: 'Shapes & Attributes',
    icon: '△',
    perPage: 16,
    offered: (grade: GradeConfig) => grade.available.includes('shapes'),
    scope: () => '2-D & 3-D shapes',
    generate: generateShapes
};

// The plugin: a function the dashboard calls with its framework bundle.
export function ShapesWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(shapesSpec);
}
