// ─────────────────────────────────────────────────────────────────────────────
// SKIP COUNTING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SkipCountingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Skip Counting", glyph "»") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// DEPTH-FIRST SHEET (quality over quantity): EIGHT connected tasks per A4
// page (single column — every prompt is a multi-part line with real writing
// space), instead of the old 16 single-blank runs. The runs are now DEEPER:
// two blanks per run, runs whose RULE the student must state, explicit
// "start here, count on by N" instructions, and a claim about where a skip
// sequence LANDS that the student checks (multiplicative reasoning in
// disguise — "does 37 appear when counting by 5s from 2?").
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Skip Counting worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Skip counting by an interval from skipSet, with RANDOM STARTS, over FIVE
// task families. Every printed task carries 2 blanks (or one word blank)
// whose answers are recorded in order in `answer` (comma separated —
// RawProblem allows it), so the answer key covers EVERY requested part:
//   twoBlanks — "s, s+i, __, s+3i, __"          (two gaps, one forward run)
//   rule      — "s, s+i, s+2i, s+3i, __; it counts by __" (next term AND the
//               rule — stating the interval is the Y2 reasoning ask)
//   backTwo   — "s, s-i, s-2i, __, __"          (count BACK, two blanks)
//   countOn   — "Start at s and count on by i: s, __, __" (rule given, the
//               student executes it twice)
//   lands     — "Does counting by i from s land on t? __" — Correct/Wrong:
//               t is on the sequence exactly when (t - s) is a multiple of i
// The start is drawn so the whole printed run stays inside [0, skipCap], and
// the interval is dealt from a deck so every enabled interval appears before
// any repeats.
//
// NON-REPEATING SAMPLING: intervals AND starts are drawn through the shared
// rng and the whole question passes through sampleUnique keyed on the printed
// prompt, so the same interval with a different start (or blank position) is
// a fresh question — the space (intervals x starts x forms) stays deep for
// every grade and never repeats inside a document.
const SKIP_FORMS = ['twoBlanks', 'rule', 'backTwo', 'countOn', 'lands'] as const;

function generateSkip(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const intervals = caps.skipSet.length ? [...caps.skipSet] : [1];
    const intervalDeck = createDeck(rng, intervals);
    const formDeck = createDeck(rng, SKIP_FORMS);
    return sampleUnique(
        count,
        () => {
            const interval = intervalDeck.take();
            const form = formDeck.take();
            if (form === 'twoBlanks') {
                // Forward run with gaps at positions 2 and 4 (0-based): the
                // student holds the interval across BOTH blanks.
                const maxStart = Math.max(0, caps.skipCap - 4 * interval);
                const start = rng.int(0, maxStart);
                return {
                    prompt: `${start}, ${start + interval}, __, ${start + 3 * interval}, __`,
                    answer: `${start + 2 * interval}, ${start + 4 * interval}`
                };
            }
            if (form === 'rule') {
                // Next term AND the rule: four shown terms pin the interval
                // unambiguously, so the "counts by __" blank is checkable.
                const maxStart = Math.max(0, caps.skipCap - 4 * interval);
                const start = rng.int(0, maxStart);
                return {
                    prompt: `${start}, ${start + interval}, ${start + 2 * interval}, ${start + 3 * interval}, __; it counts by __`,
                    answer: `${start + 4 * interval}, ${interval}`
                };
            }
            if (form === 'backTwo') {
                // Backward run, two blanks: the start is at least 4 intervals
                // so both answers stay non-negative.
                const minStart = 4 * interval;
                const start = rng.int(minStart, Math.max(minStart, caps.skipCap));
                return {
                    prompt: `${start}, ${start - interval}, ${start - 2 * interval}, __, __`,
                    answer: `${start - 3 * interval}, ${start - 4 * interval}`
                };
            }
            if (form === 'countOn') {
                // EXECUTE a given rule twice from an arbitrary start — the
                // interval is printed, the blanks are the two jumps.
                const maxStart = Math.max(0, caps.skipCap - 2 * interval);
                const start = rng.int(0, maxStart);
                return {
                    prompt: `Start at ${start} and count on by ${interval}: ${start}, __, __`,
                    answer: `${start + interval}, ${start + 2 * interval}`
                };
            }
            // LANDS: a yes/no claim about membership of the skip sequence.
            // The answer word goes in a WIDE blank; the underlying check —
            // (t - start) divisible by the interval — is the reasoning.
            const start = rng.int(0, Math.max(0, caps.skipCap - 1));
            // Draw the target so BOTH outcomes occur and t always stays
            // within skipCap: half the time an exact jump ahead (a guaranteed
            // "Correct"), half the time any later value (often off-sequence).
            const kMax = Math.floor((caps.skipCap - start) / interval);
            const t = kMax >= 1 && rng.next() < 0.5
                ? start + interval * rng.int(1, kMax)
                : rng.int(start + 1, Math.max(start + 1, caps.skipCap));
            const lands = t > start && (t - start) % interval === 0;
            return {
                prompt: `Does counting by ${interval} from ${start} land on ${t}? __`,
                answer: lands ? 'Correct' : 'Wrong',
                wideBlanks: true
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const skipSpec: WorksheetSpec = {
    id: 'skip',
    label: 'Skip Counting',
    icon: '»',
    // Eight connected multi-part tasks per A4, printed in ONE column so every
    // run has the full page width and the rows stretch to fill the sheet —
    // fewer questions, far more thinking and writing space each.
    perPage: 8,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('skip'),
    scope: (grade: GradeConfig) => `count by ${[...grade.caps.skipSet].sort((a, b) => a - b).join(', ')}`,
    generate: generateSkip
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SkipCountingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(skipSpec);
}
