// ─────────────────────────────────────────────────────────────────────────────
// SKIP COUNTING WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SkipCountingWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Skip Counting", glyph "»") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Skip Counting worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Skip counting: "count on" by an interval from skipSet. We print the first
// three terms and ask for the fourth (4 x interval). If the chosen interval
// would push the 4th term past skipCap we fall back to the smallest interval,
// which is always small enough.
function generateSkip(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const fallback = caps.skipSet.length ? Math.min(...caps.skipSet) : 1;
    for (let i = 0; i < count; i++) {
        let interval = caps.skipSet.length ? rng.pick(caps.skipSet) : 1;
        if (interval * 4 > caps.skipCap) interval = fallback;
        out.push({
            prompt: `${interval}, ${interval * 2}, ${interval * 3}, __`,
            answer: `${interval * 4}`
        });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const skipSpec: WorksheetSpec = {
    id: 'skip',
    label: 'Skip Counting',
    icon: '»',
    perPage: 16,
    offered: (grade: GradeConfig) => grade.available.includes('skip'),
    scope: (grade: GradeConfig) => `count by ${[...grade.caps.skipSet].sort((a, b) => a - b).join(', ')}`,
    generate: generateSkip
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SkipCountingWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(skipSpec);
}
