// ─────────────────────────────────────────────────────────────────────────────
// SUBTRACTION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SubtractionWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Subtraction", glyph "−") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Subtraction worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Subtraction within opCap. b is chosen strictly below a so every answer is a
// positive whole number (no negative results, no trivial "x - x = 0").
function generateSubtraction(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const aMax = Math.max(2, caps.opCap);
    for (let i = 0; i < count; i++) {
        const a = rng.int(2, aMax);
        const b = rng.int(0, a - 1); // b < a  =>  a - b >= 1
        out.push({ prompt: `${a} - ${b} = __`, answer: `${a - b}` });
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const subtractionSpec: WorksheetSpec = {
    id: 'subtraction',
    label: 'Subtraction',
    icon: '−',
    perPage: 24,
    offered: (grade: GradeConfig) => grade.available.includes('subtraction'),
    scope: (grade: GradeConfig) => `within ${grade.caps.opCap}`,
    generate: generateSubtraction
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SubtractionWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(subtractionSpec);
}
