// ─────────────────────────────────────────────────────────────────────────────
// SUBTRACTION WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `SubtractionWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Subtraction", glyph "−") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// DEPTH-FIRST SHEET (quality over quantity): EIGHT connected tasks per A4
// page (single column — every prompt is a multi-part line with real writing
// space), instead of the old 24 shallow "a - b = __" drills. Every task asks
// 2–3 connected things at once: the difference AND its partner addition,
// two differences AND their distance apart, checking a true/false claim and
// fixing it, and the inverse-operation (add-back) check after a column or
// multi-subtrahend calculation.
//
// DIFFICULTY LADDER (grade 0..6), driven entirely by the grade catalogue
// (framework/grades.ts — arithmeticLadderGrade, shared with the Addition
// plugin):
//   Prep (0)  within 10        | Year 4  within 10 000,   up to 2 subtrahends
//   Year 1    within 20        | Year 5  within 100 000,  up to 2 subtrahends
//   Year 2    within 100       | Year 6  within 1 000 000, up to 3 subtrahends
//   Year 3    within 1 000     |
// Grade 7 and above do not offer subtraction at all (their `available` list
// in grades.ts is empty — the ladder is finished by Year 6).
//
// Fully self-contained: deleting this file and its line in plugins/index.ts
// removes the Subtraction worksheet without affecting the framework or any
// other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Difficulty is read from two caps:
//   - caps.opCap     — the "within N" ceiling for the minuend;
//   - caps.addendCap — the ladder's shared term cap: addition uses up to
//                      addendCap addends, so subtraction uses up to
//                      (addendCap - 1) subtrahends (2 => classic a - b pairs,
//                      3 => a - b - c from Year 4, 4 => a - b - c - d in Y6).
//
// PAIR RECIPE (shared by every pair-based form): b is chosen at least 1 and
// strictly below a, so every difference is a POSITIVE whole number and the
// trivial "a - 0" never prints (the old sheet showed it; depth-first, the
// subtracting-zero case adds no practice).
function drawPair(rng: Rng, cap: number): [number, number] {
    const a = rng.int(2, Math.max(2, cap));
    const b = rng.int(1, a - 1); // 1 <= b < a  =>  a - b >= 1
    return [a, b];
}

// The task families. Every printed task carries 2–3 blanks whose answers are
// recorded in order in `answer` (comma separated — RawProblem allows it), so
// the answer key covers EVERY requested part:
//   partner  — "a - b = __ and __ + b = a"          (fact-family partner)
//   diff     — two differences then "the differences differ by __"
//   verify   — true/false claim + correction        (checking, word blank)
//   column   — Year 3 vertical column + add-back check (ColumnDiagram figure)
//   multi    — Year 4+ multi-subtrahend chain + add-back check
const SUBTRACTION_FORMS_PAIR = ['partner', 'diff', 'verify'] as const;
const SUBTRACTION_FORMS_COLUMN = ['partner', 'diff', 'verify', 'column'] as const;
const SUBTRACTION_FORMS_MULTI = ['partner', 'diff', 'verify', 'multi'] as const;

// NON-REPEATING SAMPLING: the family is dealt from a deck (every family
// appears before any repeats) and the whole question passes through
// sampleUnique keyed on the printed prompt, so a document holds each distinct
// task once before the space cycles.
function generateSubtraction(rng: Rng, caps: Caps, count: number): RawProblem[] {
    // Max subtrahends for this grade: the pair grades (addendCap 2) stay
    // single-subtraction; 0/undefined (unimplemented grades) behaves the same.
    const maxSubtrahends = Math.max(1, (caps.addendCap || 2) - 1);
    // Year 3 (caps.opCap === 1000) is the multi-digit pair grade: its column
    // tasks print a right-aligned vertical column (framework/ColumnDiagram.tsx)
    // with the "−" marker before the subtrahend — the established Year-3-only
    // figure gate (grades.ts ladder).
    const forms = maxSubtrahends > 1 ? SUBTRACTION_FORMS_MULTI : caps.opCap === 1000 ? SUBTRACTION_FORMS_COLUMN : SUBTRACTION_FORMS_PAIR;
    const formDeck = createDeck(rng, forms);
    return sampleUnique(
        count,
        () => {
            const form = formDeck.take();
            if (form === 'partner') {
                // COMPUTE, then REUSE: the difference the student just found
                // is the missing addend of the partner fact — the fact family
                // made explicit.
                const [a, b] = drawPair(rng, caps.opCap);
                const d = a - b;
                return { prompt: `${a} - ${b} = __ and __ + ${b} = ${a}`, answer: `${d}, ${d}` };
            }
            if (form === 'diff') {
                // COMPUTE BOTH, then COMPARE: the third blank is the distance
                // between the two differences (0 is legitimate and
                // instructive). The second pair is redrawn while it is the
                // IDENTICAL ordered pair, so the line never prints the very
                // same statement twice.
                const [a, b] = drawPair(rng, caps.opCap);
                let [c, d] = drawPair(rng, caps.opCap);
                let guard = 0;
                while (c === a && d === b && guard++ < 10) [c, d] = drawPair(rng, caps.opCap);
                const d1 = a - b;
                const d2 = c - d;
                return {
                    prompt: `${a} - ${b} = __ and ${c} - ${d} = __; the differences differ by __`,
                    answer: `${d1}, ${d2}, ${Math.abs(d1 - d2)}`
                };
            }
            if (form === 'verify') {
                // CHECK a claim, then FIX it. The claim is correct ~1/3 of the
                // time; a wrong claim is off by 1 or 2 and stays a plausible
                // positive difference within the grade's ceiling.
                const [a, b] = drawPair(rng, caps.opCap);
                const d = a - b;
                let claim = d;
                if (rng.next() < 2 / 3) {
                    const delta = rng.int(1, 2);
                    const upOk = d + delta <= caps.opCap;
                    const downOk = d - delta >= 1;
                    if (upOk && downOk) claim = rng.next() < 0.5 ? d + delta : d - delta;
                    else claim = upOk ? d + delta : d - delta;
                }
                return {
                    prompt: `True or false: ${a} - ${b} = ${claim}. __; if it is wrong, fix it: ${a} - ${b} = __`,
                    answer: `${claim === d ? 'Correct' : 'Wrong'}, ${d}`,
                    // The first blank takes the WORD ("Correct"/"Wrong").
                    wideBlanks: true
                };
            }
            if (form === 'column') {
                // Year 3: subtract in the printed column (figure repeats the
                // terms, never the result), then CHECK by adding the answer
                // back to the subtrahend — the inverse operation.
                const [a, b] = drawPair(rng, caps.opCap);
                const d = a - b;
                return {
                    prompt: `Subtract, then check: ${a} - ${b} = __; check: ${d} + ${b} = __`,
                    answer: `${d}, ${a}`,
                    column: { terms: [a, b], op: '-' }
                };
            }
            // MULTI-SUBTRAHEND + CHECK (Year 4+): the minuend is drawn first,
            // large enough that every subtrahend can be >= 1 AND the final
            // answer >= 1 (so no negatives and no trivial "x - x = 0"). Each
            // subtrahend reserves 1 for every still-to-come subtrahend plus 1
            // for the final answer. The check adds the subtrahends back in
            // REVERSE order — its answer is the original minuend.
            const s = maxSubtrahends > 1 ? rng.int(1, maxSubtrahends) : 1;
            const a = rng.int(s + 1, Math.max(2, caps.opCap));
            let remaining = a;
            const parts: number[] = [];
            for (let j = 0; j < s; j++) {
                const left = s - j - 1; // subtrahends still to place after this one
                const v = rng.int(1, Math.max(1, remaining - left - 1));
                parts.push(v);
                remaining -= v;
            }
            // What is left after every subtraction IS the first answer.
            const back = [...parts].reverse().join(' + ');
            return {
                prompt: `${a} - ${parts.join(' - ')} = __; check: ${remaining} + ${back} = __`,
                answer: `${remaining}, ${a}`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const subtractionSpec: WorksheetSpec = {
    id: 'subtraction',
    label: 'Subtraction',
    icon: '−',
    // SEVEN connected multi-part tasks per A4, printed in ONE column so every
    // line has the full page width and the rows stretch to fill the sheet —
    // fewer questions, far more thinking and writing space each.
    // LAYOUT CAPACITY (T3M3): the Year-3 vertical-column form is the tallest
    // row — one prompt line (21.6px) + ColumnDiagram block (6+81px) = 102.6px.
    // At 8/page the fixed 1fr row is only 93.3px (overflow); at 7/page it is
    // 110.0px (margin 7.4). See plugins/layout-capacity.test.ts for the model.
    perPage: 7,
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('subtraction'),
    // "within 20" for the pair grades; the multi-subtrahend grades (Year 4+)
    // advertise the second difficulty axis as well.
    scope: (grade: GradeConfig) =>
        grade.caps.addendCap > 2
            ? `within ${grade.caps.opCap} (up to ${grade.caps.addendCap - 1} subtrahends)`
            : `within ${grade.caps.opCap}`,
    generate: generateSubtraction
};

// The plugin: a function the dashboard calls with its framework bundle.
export function SubtractionWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(subtractionSpec);
}
