// ─────────────────────────────────────────────────────────────────────────────
// TEMPERATURE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `TemperatureWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Temperature", glyph "♨") and which grades offer it
//     (a Year 1+ extension type; grade-1 level content — warm/cold language,
//     reading and comparing °C values, small rises/drops);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Questions mix
//     short comparisons with worded items (and one write-on-the-line
//     ordering item), so the sheet prints single-column.
//
// Fully self-contained: the temperature vocabulary lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Temperature
// worksheet without affecting the framework or any other plugin.
//
// CURRICULUM: grade-1 measurement sense (V9 F-2 measurement thread,
// AC9M1M02 "compare directly... using everyday language") extended to
// temperature — compare warmer/colder days, read °C values within the grade's
// cap (caps.tempCap: 20 for Year 1, 40 for Year 2), add/subtract small
// degree changes within the same range, and know the thermometer facts.
//
// DEPTH DESIGN (quality over quantity): eight connected items per page.
// The families now chain instead of isolating:
//   chain        — Mon→Tue→Wed two-step weather story (b continues from a)
//   compareDiff  — which is warmer/colder AND by how many degrees
//   errorCheck   — judge a friend's "warmest is…" claim, then correct it
//   freezeUp/Down— rise/drop AND whether the new reading moved closer to or
//                  further from freezing (0°C) — number-line reasoning
//   warmestDiff  — warmest of three AND warmest-minus-coldest
//   order        — write the full coldest→warmest list on the answer line
//   season/fact  — everyday-context and thermometer knowledge (kept)
// Every multi-part answer string lists BOTH part results in printed order.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// One-line thermometer facts kids are expected to know (fixed pool — the
// Australian seasons item keeps the southern-hemisphere framing consistent
// with the Time & Calendar sheet's seasons).
const TEMPERATURE_FACTS: readonly [string, string][] = [
    ['What do we measure temperature with? __', 'a thermometer'],
    ['What does the °C on a weather chart stand for? __', 'Celsius'],
    ['At what temperature does water freeze? __', '0°C'],
    ['Which season has the coldest days in Australia? __', 'winter'],
    ['Which season has the hottest days in Australia? __', 'summer']
];

// Everyday contexts for the "more likely" kind. Hot contexts pair a value
// from the top of the grade's range against one from the bottom, so the
// correct answer is unambiguous for a grade-1 reader.
const HOT_CONTEXTS = ['a hot day at the beach', 'a sunny Christmas picnic', 'a summer day at the pool'] as const;
const COLD_CONTEXTS = ['a snowy winter morning', 'an icy winter night', 'a cold day in the snow'] as const;

// Three distinct temperatures with pairwise gaps >= 2 — keeps "which is the
// warmest of three" from ever being a near-tie (and guarantees the ordering
// item has clearly separated rungs for a grade-1 student).
function pickThreeTemps(rng: Rng, cap: number): number[] {
    const temps: number[] = [];
    while (temps.length < 3) {
        const t = rng.int(1, cap);
        if (temps.every((u) => Math.abs(u - t) >= 2)) temps.push(t);
    }
    return temps;
}

// Two values with a gap >= 2 — never a one-degree coin flip.
function pickPair(rng: Rng, cap: number): [number, number] {
    const a = rng.int(1, cap);
    let b = rng.int(1, cap);
    while (Math.abs(b - a) < 2) b = rng.int(1, cap);
    return [a, b];
}

// Temperature (grade-1 measurement sense): chained day-by-day rises/drops,
// warmer/colder comparisons WITH the difference, error analysis of a friend's
// claim, freezing-point number-line reasoning, warmest-of-three with its
// spread, ordering on a writing line, everyday hot/cold contexts and
// thermometer facts. The numeric range comes from caps.tempCap (20 for Year 1,
// 40 for Year 2); 0 would mean "not offered", which buildDocument gates away
// before the generator runs — the Math.max floor below only guards a
// misconfigured catalogue. EVERY constraint keeps intermediate answers inside
// 1..cap: no below-zero readings and no totals above the grade's cap.
//
// NON-REPEATING SAMPLING: every question passes through sampleUnique keyed
// on the printed prompt, so the same comparison (in either display order)
// never prints twice before its space has been dealt.
function generateTemperature(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(10, caps.tempCap);
    // Kindness bands for the "more likely" kind: "hot" answers sit in the top
    // third of the range, "cold" answers in the bottom quarter.
    const hotLo = Math.ceil(cap * 0.7);
    const coldHi = Math.max(3, Math.floor(cap * 0.25));
    // Facts dealt from a deck so the five fixed items spread evenly across a
    // long document instead of clumping on lucky picks.
    const factDeck = createDeck(rng, TEMPERATURE_FACTS);
    return sampleUnique(
        count,
        () => {
            const kinds: string[] = [
                'chain',
                'warmerDiff',
                'colderDiff',
                'errorCheck',
                'freezeUp',
                'freezeDown',
                'warmestDiff',
                'order',
                'season',
                'fact'
            ];
            const kind = rng.pick(kinds);
            switch (kind) {
                case 'chain': {
                    // Two-step weather story: (b) continues from (a)'s answer.
                    // t1 ≥ 4 and t1 ≤ cap-6 leave room for +d1 then -d2 while
                    // every reading stays inside 1..cap.
                    const t1 = rng.int(4, cap - 6);
                    const d1 = rng.int(1, 5);
                    const t2 = t1 + d1;
                    const d2 = rng.int(1, Math.min(5, t2 - 1));
                    const t3 = t2 - d2;
                    return {
                        prompt:
                            `On Monday the temperature is ${t1}°C. Tuesday is ${d1} degrees warmer than Monday. Wednesday is ${d2} degrees colder than Tuesday.\n` +
                            `(a) What is Tuesday's temperature? __\n` +
                            `(b) What is Wednesday's temperature? __`,
                        answer: `${t2}°C, ${t3}°C`
                    };
                }
                case 'warmerDiff': {
                    // Comparison AND the size of the gap.
                    const [a, b] = pickPair(rng, cap);
                    return {
                        prompt:
                            `(a) Which is warmer: ${a}°C or ${b}°C? __\n` +
                            `(b) How many degrees warmer is it? __`,
                        answer: `${Math.max(a, b)}°C, ${Math.abs(a - b)} degrees`
                    };
                }
                case 'colderDiff': {
                    const [a, b] = pickPair(rng, cap);
                    return {
                        prompt:
                            `(a) Which is colder: ${a}°C or ${b}°C? __\n` +
                            `(b) How many degrees colder is it? __`,
                        answer: `${Math.min(a, b)}°C, ${Math.abs(a - b)} degrees`
                    };
                }
                case 'errorCheck': {
                    // Error analysis: half the claims are right, so the
                    // student must actually compare the three readings.
                    const temps = pickThreeTemps(rng, cap);
                    const max = Math.max(...temps);
                    const saysMax = rng.next() < 0.5;
                    const claimed = saysMax ? max : temps.find((t) => t !== max)!;
                    const name = ['Sam', 'Mia', 'Leo', 'Zoe'][rng.int(0, 3)];
                    return {
                        prompt:
                            `${name} says the warmest of ${temps[0]}°C, ${temps[1]}°C and ${temps[2]}°C is ${claimed}°C.\n` +
                            `(a) Is ${name} correct? __\n` +
                            `(b) What is the actual warmest temperature? __`,
                        answer: `${saysMax ? 'yes' : 'no'}, ${max}°C`
                    };
                }
                case 'freezeUp': {
                    // Rise + distance-from-freezing reasoning (0°C anchor).
                    const t = rng.int(2, cap - 5);
                    const d = rng.int(1, Math.min(5, cap - t));
                    return {
                        prompt:
                            `It is ${t}°C now. The temperature rises by ${d} degrees.\n` +
                            `(a) What is the temperature now? __\n` +
                            `(b) Is the new temperature closer to or further from freezing (0°C) than before? __`,
                        answer: `${t + d}°C, further`
                    };
                }
                case 'freezeDown': {
                    // Drop that never crosses zero (below-zero reading is out
                    // of scope for this sheet), plus the same 0°C reasoning.
                    const t = rng.int(6, cap);
                    const d = rng.int(1, Math.min(5, t - 1));
                    return {
                        prompt:
                            `It is ${t}°C now. The temperature drops by ${d} degrees.\n` +
                            `(a) What is the temperature now? __\n` +
                            `(b) Is the new temperature closer to or further from freezing (0°C) than before? __`,
                        answer: `${t - d}°C, closer`
                    };
                }
                case 'warmestDiff': {
                    // Warmest of three AND the spread (warmest − coldest).
                    const [a, b, c] = pickThreeTemps(rng, cap);
                    const max = Math.max(a, b, c);
                    const min = Math.min(a, b, c);
                    return {
                        prompt:
                            `(a) Which is the warmest: ${a}°C, ${b}°C or ${c}°C? __\n` +
                            `(b) What is the difference between the warmest and the coldest? __`,
                        answer: `${max}°C, ${max - min} degrees`
                    };
                }
                case 'order': {
                    // Ordering item: the three temps print in the sampled
                    // order (swapped out of ascending position so the answer
                    // is never already given away) and the student writes the
                    // coldest→warmest list on the full-width line below.
                    const temps = pickThreeTemps(rng, cap);
                    if (temps[0] < temps[1] && temps[1] < temps[2]) {
                        [temps[0], temps[2]] = [temps[2], temps[0]];
                    }
                    const sorted = [...temps].sort((x, y) => x - y);
                    return {
                        prompt: `Put these temperatures in order from coldest to warmest: ${temps[0]}°C, ${temps[1]}°C, ${temps[2]}°C`,
                        answer: sorted.map((t) => `${t}°C`).join(', '),
                        answerLine: true
                    };
                }
                case 'season': {
                    // Everyday context: pick the matching band for the context
                    // (hot band for beach/pool days, cold band for snow/ice)
                    // and present it against the opposite band in random
                    // display order.
                    const isHot = rng.pick([true, false]);
                    const context = isHot ? rng.pick(HOT_CONTEXTS) : rng.pick(COLD_CONTEXTS);
                    const right = isHot ? rng.int(hotLo, cap) : rng.int(1, coldHi);
                    const wrong = isHot ? rng.int(1, coldHi) : rng.int(hotLo, cap);
                    const [x, y] = rng.pick([
                        [right, wrong],
                        [wrong, right]
                    ]);
                    return { prompt: `Is ${context} more likely to be ${x}°C or ${y}°C? __`, answer: `${right}°C` };
                }
                default: {
                    const [prompt, answer] = factDeck.take();
                    return { prompt, answer };
                }
            }
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const temperatureSpec: WorksheetSpec = {
    id: 'temperature',
    label: 'Temperature',
    icon: '♨',
    // Eight connected items per page — the multi-part stories and ordering
    // line need the space the old density of 12 did not leave.
    perPage: 8,
    // Mixes short comparisons with worded items — prints single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('temperature'),
    // The numeric scope straight from the grade cap: "temperatures to 20°C"
    // (Year 1) / "temperatures to 40°C" (Year 2).
    scope: (grade: GradeConfig) => `temperatures to ${grade.caps.tempCap}°C`,
    generate: generateTemperature
};

// The plugin: a function the dashboard calls with its framework bundle.
export function TemperatureWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(temperatureSpec);
}
