// ─────────────────────────────────────────────────────────────────────────────
// TEMPERATURE WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `TemperatureWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Temperature", glyph "♨") and which grades offer it
//     (a Year 1+ extension type; grade-1 level content — warm/cold language,
//     reading and comparing °C values, small rises/drops);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). Questions mix
//     short comparisons with worded items (and one write-on-the-line
//     ordering item), so the sheet prints single-column.
//
// Fully self-contained: the temperature vocabulary lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Temperature
// worksheet without affecting the framework or any other plugin.
//
// CURRICULUM: grade-1 measurement sense (V9 F-2 measurement thread,
// AC9M1M02 "compare directly... using everyday language") extended to
// temperature — compare warmer/colder days, read °C values within the grade's
// cap (caps.tempCap: 20 for Year 1, 40 for Year 2), add/subtract small
// degree changes within the same range, and know the thermometer facts.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// One-line thermometer facts kids are expected to know (fixed pool — the
// Australian seasons item keeps the southern-hemisphere framing consistent
// with the Time & Calendar sheet's seasons).
const TEMPERATURE_FACTS: readonly [string, string][] = [
    ['What do we measure temperature with?', 'a thermometer'],
    ['What does the °C on a weather chart stand for?', 'Celsius'],
    ['At what temperature does water freeze?', '0°C'],
    ['Which season has the coldest days in Australia?', 'winter'],
    ['Which season has the hottest days in Australia?', 'summer']
];

// Everyday contexts for the "more likely" kind. Hot contexts pair a value
// from the top of the grade's range against one from the bottom, so the
// correct answer is unambiguous for a grade-1 reader.
const HOT_CONTEXTS = ['a hot day at the beach', 'a sunny Christmas picnic', 'a summer day at the pool'] as const;
const COLD_CONTEXTS = ['a snowy winter morning', 'an icy winter night', 'a cold day in the snow'] as const;

// Three distinct temperatures with pairwise gaps >= 2 — keeps "which is the
// warmest of three" from ever being a near-tie (and guarantees the ordering
// item has clearly separated rungs for a grade-1 student).
function pickThreeTemps(rng: Rng, cap: number): number[] {
    const temps: number[] = [];
    while (temps.length < 3) {
        const t = rng.int(1, cap);
        if (temps.every((u) => Math.abs(u - t) >= 2)) temps.push(t);
    }
    return temps;
}

// Temperature (grade-1 measurement sense): warmer/colder comparisons, small
// rises and drops (arithmetic stays within the grade's temperature cap),
// warmest/coldest of three, order-from-coldest-to-warmest on a writing line,
// everyday hot/cold contexts and thermometer facts. The numeric range comes
// from caps.tempCap (20 for Year 1, 40 for Year 2); 0 would mean "not
// offered", which buildDocument gates away before the generator runs — the
// Math.max floor below only guards a misconfigured catalogue.
//
// NON-REPEATING SAMPLING: every question passes through sampleUnique keyed
// on the printed prompt, so the same comparison (in either display order)
// never prints twice before its space has been dealt.
function generateTemperature(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(10, caps.tempCap);
    // Kindness bands for the "more likely" kind: "hot" answers sit in the top
    // third of the range, "cold" answers in the bottom quarter.
    const hotLo = Math.ceil(cap * 0.7);
    const coldHi = Math.max(3, Math.floor(cap * 0.25));
    // Facts dealt from a deck so the five fixed items spread evenly across a
    // long document instead of clumping on lucky picks.
    const factDeck = createDeck(rng, TEMPERATURE_FACTS);
    return sampleUnique(
        count,
        () => {
            const kinds: string[] = [
                'warmer',
                'colder',
                'up',
                'down',
                'warmest',
                'coldest',
                'order',
                'season',
                'fact'
            ];
            const kind = rng.pick(kinds);
            switch (kind) {
                case 'warmer': {
                    // Two values with a gap >= 2 — never a one-degree coin flip.
                    const a = rng.int(1, cap);
                    let b = rng.int(1, cap);
                    while (Math.abs(b - a) < 2) b = rng.int(1, cap);
                    return { prompt: `Which is warmer: ${a}°C or ${b}°C?`, answer: `${Math.max(a, b)}°C` };
                }
                case 'colder': {
                    const a = rng.int(1, cap);
                    let b = rng.int(1, cap);
                    while (Math.abs(b - a) < 2) b = rng.int(1, cap);
                    return { prompt: `Which is colder: ${a}°C or ${b}°C?`, answer: `${Math.min(a, b)}°C` };
                }
                case 'up': {
                    // Rise: start + delta never exceeds the grade's cap, so a
                    // Year 1 sheet's answers stay within 20.
                    const start = rng.int(2, cap - 5);
                    const delta = rng.int(1, Math.min(5, cap - start));
                    return {
                        prompt: `It is ${start}°C outside. The temperature goes up by ${delta} degrees. What is the temperature now?`,
                        answer: `${start + delta}°C`
                    };
                }
                case 'down': {
                    // Drop: never falls below 1°C (below-zero reading is out of
                    // scope for the grade-1 sheet).
                    const start = rng.int(6, cap);
                    const delta = rng.int(1, Math.min(5, start - 1));
                    return {
                        prompt: `It is ${start}°C outside. The temperature goes down by ${delta} degrees. What is the temperature now?`,
                        answer: `${start - delta}°C`
                    };
                }
                case 'warmest': {
                    const [a, b, c] = pickThreeTemps(rng, cap);
                    return {
                        prompt: `Which is the warmest: ${a}°C, ${b}°C or ${c}°C?`,
                        answer: `${Math.max(a, b, c)}°C`
                    };
                }
                case 'coldest': {
                    const [a, b, c] = pickThreeTemps(rng, cap);
                    return {
                        prompt: `Which is the coldest: ${a}°C, ${b}°C or ${c}°C?`,
                        answer: `${Math.min(a, b, c)}°C`
                    };
                }
                case 'order': {
                    // Ordering item: the three temps print in the sampled
                    // order (swapped out of ascending position so the answer
                    // is never already given away) and the student writes the
                    // coldest→warmest list on the full-width line below.
                    const temps = pickThreeTemps(rng, cap);
                    if (temps[0] < temps[1] && temps[1] < temps[2]) {
                        [temps[0], temps[2]] = [temps[2], temps[0]];
                    }
                    const sorted = [...temps].sort((x, y) => x - y);
                    return {
                        prompt: `Put these temperatures in order from coldest to warmest: ${temps[0]}°C, ${temps[1]}°C, ${temps[2]}°C`,
                        answer: sorted.map((t) => `${t}°C`).join(', '),
                        answerLine: true
                    };
                }
                case 'season': {
                    // Everyday context: pick the matching band for the context
                    // (hot band for beach/pool days, cold band for snow/ice)
                    // and present it against the opposite band in random
                    // display order.
                    const isHot = rng.pick([true, false]);
                    const context = isHot ? rng.pick(HOT_CONTEXTS) : rng.pick(COLD_CONTEXTS);
                    const right = isHot ? rng.int(hotLo, cap) : rng.int(1, coldHi);
                    const wrong = isHot ? rng.int(1, coldHi) : rng.int(hotLo, cap);
                    const [x, y] = rng.pick([
                        [right, wrong],
                        [wrong, right]
                    ]);
                    return { prompt: `Is ${context} more likely to be ${x}°C or ${y}°C?`, answer: `${right}°C` };
                }
                default: {
                    const [prompt, answer] = factDeck.take();
                    return { prompt, answer };
                }
            }
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const temperatureSpec: WorksheetSpec = {
    id: 'temperature',
    label: 'Temperature',
    icon: '♨',
    perPage: 12,
    // Mixes short comparisons with worded items — prints single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('temperature'),
    // The numeric scope straight from the grade cap: "temperatures to 20°C"
    // (Year 1) / "temperatures to 40°C" (Year 2).
    scope: (grade: GradeConfig) => `temperatures to ${grade.caps.tempCap}°C`,
    generate: generateTemperature
};

// The plugin: a function the dashboard calls with its framework bundle.
export function TemperatureWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(temperatureSpec);
}
