// ─────────────────────────────────────────────────────────────────────────────
// TIME & CALENDAR WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `TimeWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Time & Calendar', glyph '◷') and which grades offer
//     it (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: the calendar vocabulary lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Time worksheet
// without affecting the framework or any other plugin.
//
// DEPTH DESIGN (quality over quantity): instead of sixteen isolated
// one-word answers, eight CONNECTED items per page. Most items anchor ONE
// real-world situation and ask two linked questions about it — (a)/(b) print
// on their own lines (PrintableSheet's ProblemText is white-space: pre-wrap)
// each with its own "__" response blank, and the answer string lists BOTH
// results in order. The reasoning strands: day-before AND day-after from one
// anchor, days-until plus the day before the event, month before AND after,
// month → season (Australian seasons), season-adjacent temperature reasoning,
// weekday/weekend classification, doubling calendar facts, and — Year 2 only —
// clock items that read the drawn face FIRST, then move forward or BACKWARD
// in time (the framework ClockFigure draws only the GIVEN face; answers stay
// private).
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Calendar vocabulary for the time generator (V8 ACMMG168-170: days of the
// week, months and seasons in Y1; hour & half-past clock time in Y2).
const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] as const;
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] as const;
const SEASONS = ['spring', 'summer', 'autumn', 'winter'] as const;

// Southern-hemisphere (Australian) season of each month — the same framing the
// Temperature sheet uses ("coldest days in Australia = winter"). Kept explicit
// so the generator never computes seasons from dates:
// Jan/Feb = summer, Mar/Apr/May = autumn, Jun/Jul/Aug = winter,
// Sep/Oct/Nov = spring, Dec = summer.
const AU_SEASON: readonly string[] = [
    'summer', // January
    'summer', // February
    'autumn', // March
    'autumn', // April
    'autumn', // May
    'winter', // June
    'winter', // July
    'winter', // August
    'spring', // September
    'spring', // October
    'spring', // November
    'summer' // December
];

// Coldness ranking used by the season-adjacent comparison (southern hemisphere
// everyday knowledge: winter is the coldest season, summer the hottest).
const COLD_RANK: Record<string, number> = { winter: 0, autumn: 1, spring: 2, summer: 3 };

// Time & calendar (V8 ACMMG168-170; V9 AC9M2M04). Connected two-part kinds:
// dayBoth, dayUntil, monthBoth, monthSeason, seasonNext, weekday, plus the
// doubling calendar facts — and, only when clockCap > 0 (Year 2), the clock
// kinds clockBoth / clockAgo / halfBoth anchored on a drawn GIVEN face.
//
// NON-REPEATING SAMPLING: days, months and seasons are dealt from decks (the
// finite calendar vocabularies each appear once per cycle) and every question
// passes through sampleUnique keyed on the printed prompt PLUS the clock
// figure (the clock kinds' sentences are fixed — the face carries the time).
// The clock kinds are PROCEDURAL (12 faces × 2 offsets × 3 kinds), so Year 2's
// space stays deep even though the calendar vocabulary is finite and curated.
function generateTime(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const clock = caps.clockCap > 0;
    const dayDeck = createDeck(rng, DAYS);
    const monthDeck = createDeck(rng, MONTHS);
    const seasonDeck = createDeck(rng, SEASONS);
    return sampleUnique(
        count,
        () => {
            const kinds: string[] = ['dayBoth', 'dayUntil', 'monthBoth', 'monthSeason', 'seasonNext', 'weekday', 'factWeek', 'factMonth', 'factYear'];
            if (clock) kinds.push('clockBoth', 'clockAgo', 'halfBoth');
            const kind = rng.pick(kinds);
            switch (kind) {
                case 'dayBoth': {
                    // One anchor day, both neighbours: yesterday AND tomorrow.
                    const d = dayDeck.take();
                    const j = DAYS.indexOf(d);
                    return {
                        prompt:
                            `Today is ${d}.\n` +
                            `(a) What day was yesterday? __\n` +
                            `(b) What day will it be tomorrow? __`,
                        answer: `${DAYS[(j + 6) % 7]}, ${DAYS[(j + 1) % 7]}`
                    };
                }
                case 'dayUntil': {
                    // Counting forward to an event, then the day BEFORE it —
                    // forward and backward on the same week.
                    const i1 = rng.int(0, 4);
                    const i2 = rng.int(i1 + 1, 6);
                    return {
                        prompt:
                            `Today is ${DAYS[i1]}. Grandma arrives on ${DAYS[i2]}.\n` +
                            `(a) How many days is it until Grandma arrives? __\n` +
                            `(b) What day is the day BEFORE she arrives? __`,
                        answer: `${i2 - i1}, ${DAYS[i2 - 1]}`
                    };
                }
                case 'monthBoth': {
                    const m = monthDeck.take();
                    const mi = MONTHS.indexOf(m);
                    return {
                        prompt:
                            `My birthday is in ${m}.\n` +
                            `(a) What month comes just BEFORE ${m}? __\n` +
                            `(b) What month comes just AFTER ${m}? __`,
                        answer: `${MONTHS[(mi + 11) % 12]}, ${MONTHS[(mi + 1) % 12]}`
                    };
                }
                case 'monthSeason': {
                    // Month sequence feeding real-world season knowledge.
                    const m = monthDeck.take();
                    const mi = MONTHS.indexOf(m);
                    const next = (mi + 1) % 12;
                    return {
                        prompt:
                            `We are in ${m} now.\n` +
                            `(a) What month comes after ${m}? __\n` +
                            `(b) What season is ${MONTHS[next]} in Australia? __`,
                        answer: `${MONTHS[next]}, ${AU_SEASON[next]}`
                    };
                }
                case 'seasonNext': {
                    // Adjacent seasons compared for coldness (never a tie:
                    // neighbouring seasons always differ in COLD_RANK).
                    const s = seasonDeck.take();
                    const k = SEASONS.indexOf(s);
                    const next = SEASONS[(k + 1) % 4];
                    const colder = COLD_RANK[s] < COLD_RANK[next] ? s : next;
                    return {
                        prompt:
                            `It is ${s} in Australia.\n` +
                            `(a) What season comes after ${s}? __\n` +
                            `(b) Which is colder there, ${s} or ${next}? __`,
                        answer: `${next}, ${colder}`
                    };
                }
                case 'weekday': {
                    // Yesterday's NAME feeding weekday/weekend classification.
                    const d = dayDeck.take();
                    const j = DAYS.indexOf(d);
                    const y = DAYS[(j + 6) % 7];
                    const dayKind = y === 'Saturday' || y === 'Sunday' ? 'weekend' : 'weekday';
                    return {
                        prompt:
                            `Today is ${d}.\n` +
                            `(a) What day was yesterday? __\n` +
                            `(b) Was yesterday a weekday or a weekend day? __`,
                        answer: `${y}, ${dayKind}`
                    };
                }
                case 'factWeek': {
                    // Fact + doubling (14 stays inside Year 1's within-20).
                    return {
                        prompt:
                            `(a) How many days are in a week? __\n` +
                            `(b) How many days are in 2 weeks? __`,
                        answer: '7, 14'
                    };
                }
                case 'factMonth': {
                    // Fact + halving 12 (halves as equal parts are Y1 content).
                    return {
                        prompt:
                            `(a) How many months are in a year? __\n` +
                            `(b) How many months are in HALF a year? __`,
                        answer: '12, 6'
                    };
                }
                case 'factYear': {
                    return { prompt: 'How many days are in a year? __', answer: '365' };
                }
                case 'clockBoth': {
                    // Read the GIVEN face first, then move FORWARD k hours.
                    // The ClockFigure draws only the given time (PrintableSheet
                    // ClockFace) — the later answer is never drawn.
                    const h = rng.int(1, 12);
                    const k = rng.int(1, 2);
                    const h2 = ((h - 1 + k) % 12) + 1;
                    return {
                        prompt:
                            `(a) What time is showing on the clock? __\n` +
                            `(b) What time will it be ${k} ${k === 1 ? 'hour' : 'hours'} later? __`,
                        answer: `${h} o'clock, ${h2} o'clock`,
                        clock: { hour: h, minute: 0 }
                    };
                }
                case 'clockAgo': {
                    // Read the GIVEN face, then move BACKWARD — reverse time.
                    const h = rng.int(1, 12);
                    const k = rng.int(1, 2);
                    const hAgo = (((h - 1 - k) % 12) + 12) % 12 + 1;
                    return {
                        prompt:
                            `(a) What time is showing on the clock? __\n` +
                            `(b) What time was it ${k} ${k === 1 ? 'hour' : 'hours'} ago? __`,
                        answer: `${h} o'clock, ${hAgo} o'clock`,
                        clock: { hour: h, minute: 0 }
                    };
                }
                default: {
                    // 'halfBoth': read the half-past face, then one hour later.
                    const h = rng.int(1, 12);
                    return {
                        prompt:
                            `(a) What time is showing on the clock? __\n` +
                            `(b) What time will it be one hour later? __`,
                        answer: `half past ${h}, half past ${(h % 12) + 1}`,
                        clock: { hour: h, minute: 30 }
                    };
                }
            }
        },
        // Sampling key = prompt + clock figure. The three clock kinds print
        // fixed sentences — the GIVEN face IS the question (only the drawn
        // face reveals the time) — so the prompt alone would collapse the
        // 12 faces x offsets space to a handful of sentences. Keying on the
        // figure too (the DataWorksheet pattern) keeps every face a distinct
        // question; the calendar kinds carry no figure and are unaffected.
        (p) => `${p.prompt}|${p.clock ? `${p.clock.hour}:${p.clock.minute}` : ''}`
    );
}

// The plugin's declarative spec (exported for its own tests).
export const timeSpec: WorksheetSpec = {
    id: 'time',
    label: 'Time & Calendar',
    icon: '◷',
    // SIX connected items instead of sixteen one-word answers: every row
    // carries a two-part situation with real thinking (and a clock face
    // where the grade has one).
    // LAYOUT CAPACITY (T3M3): worst row = the Grandma day story, four
    // wrapped 22px prompt lines (4×33px) = 120.0px single-column; two-column
    // rows clip it (264.0px worst), so the sheet prints single-column at
    // 6/page (row 132.3px, margin 12.3).
    // See plugins/layout-capacity.test.ts for the model.
    perPage: 6,
    // Multi-part day stories wrap badly in 297px columns — print single-column.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('time'),
    scope: (grade: GradeConfig) => (grade.caps.clockCap > 0 ? 'calendar & time to the half hour' : 'days, months & seasons'),
    generate: generateTime
};

// The plugin: a function the dashboard calls with its framework bundle.
export function TimeWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(timeSpec);
}
