// ─────────────────────────────────────────────────────────────────────────────
// TIME & CALENDAR WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `TimeWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ('Time & Calendar', glyph '◷') and which grades offer
//     it (a Year 1+ extension type);
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet).
//
// Fully self-contained: the calendar vocabulary lives IN this plugin
// (duplicated deliberately — plugins never import from each other). Deleting
// this file and its line in plugins/index.ts removes the Time worksheet
// without affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Calendar vocabulary for the time generator (V8 ACMMG168-170: days of the
// week, months and seasons in Y1; hour & half-past clock time in Y2).
const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] as const;
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] as const;
const SEASONS = ['spring', 'summer', 'autumn', 'winter'] as const;
// One-line calendar facts kids are expected to know (also V8 ACMMG168-169).
const TIME_FACTS: readonly [string, string][] = [
    ['How many days are in a week?', '7'],
    ['How many months are in a year?', '12'],
    ['How many days are in a year?', '365']
];

// Time & calendar (V8 ACMMG168-170; V9 AC9M2M04). Kind pool is uniform:
// day-after/before, yesterday/tomorrow, days-until, month-after, season-after,
// calendar facts — plus clock forms (o'clock + hours-later, half-past + one
// hour later) which only appear when clockCap > 0 (i.e. Year 2).
function generateTime(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const clock = caps.clockCap > 0;
    for (let i = 0; i < count; i++) {
        const kinds: string[] = ['after', 'before', 'yesterday', 'tomorrow', 'until', 'month', 'season', 'fact'];
        if (clock) kinds.push('clock', 'half');
        const kind = rng.pick(kinds);
        switch (kind) {
            case 'after': {
                const d = rng.pick(DAYS);
                const j = DAYS.indexOf(d);
                out.push({ prompt: `What day comes after ${d}?`, answer: DAYS[(j + 1) % 7] });
                break;
            }
            case 'before': {
                const d = rng.pick(DAYS);
                const j = DAYS.indexOf(d);
                out.push({ prompt: `What day comes before ${d}?`, answer: DAYS[(j + 6) % 7] });
                break;
            }
            case 'yesterday': {
                const d = rng.pick(DAYS);
                const j = DAYS.indexOf(d);
                out.push({ prompt: `If today is ${d}, what day was yesterday?`, answer: DAYS[(j + 6) % 7] });
                break;
            }
            case 'tomorrow': {
                const d = rng.pick(DAYS);
                const j = DAYS.indexOf(d);
                out.push({ prompt: `If today is ${d}, what day is tomorrow?`, answer: DAYS[(j + 1) % 7] });
                break;
            }
            case 'until': {
                // Start Mon-Fri, target strictly later the same week.
                const i1 = rng.int(0, 4);
                const i2 = rng.int(i1 + 1, 6);
                out.push({
                    prompt: `If today is ${DAYS[i1]}, how many days is it until ${DAYS[i2]}?`,
                    answer: `${i2 - i1}`
                });
                break;
            }
            case 'month': {
                const m = rng.int(0, 11);
                out.push({ prompt: `What month comes after ${MONTHS[m]}?`, answer: MONTHS[(m + 1) % 12] });
                break;
            }
            case 'season': {
                const s = rng.pick(SEASONS);
                const k = SEASONS.indexOf(s);
                out.push({ prompt: `What season comes after ${s}?`, answer: SEASONS[(k + 1) % 4] });
                break;
            }
            case 'fact': {
                const [prompt, answer] = rng.pick(TIME_FACTS);
                out.push({ prompt, answer });
                break;
            }
            case 'clock': {
                // O'clock now, k (1-2) hours later; answer wraps at 12.
                const h = rng.int(1, 12);
                const k = rng.int(1, 2);
                const h2 = ((h - 1 + k) % 12) + 1;
                out.push({ prompt: `It is ${h} o'clock now. What time is it ${k} ${k === 1 ? 'hour' : 'hours'} later?`, answer: `${h2} o'clock` });
                break;
            }
            default: {
                // 'half': half-past h now, one hour later (half past 12 wraps back to 1).
                const h = rng.int(1, 12);
                out.push({ prompt: `It is half past ${h} now. What time is it one hour later?`, answer: `half past ${(h % 12) + 1}` });
                break;
            }
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const timeSpec: WorksheetSpec = {
    id: 'time',
    label: 'Time & Calendar',
    icon: '◷',
    perPage: 16,
    offered: (grade: GradeConfig) => grade.available.includes('time'),
    scope: (grade: GradeConfig) => (grade.caps.clockCap > 0 ? 'time to the half hour' : 'days & months'),
    generate: generateTime
};

// The plugin: a function the dashboard calls with its framework bundle.
export function TimeWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(timeSpec);
}
