// ─────────────────────────────────────────────────────────────────────────────
// WORD PROBLEMS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `WordProblemsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Word Problems", glyph "¶") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). The sheet prints
//     in a single column (prose layout, singleColumn: true).
//
// Fully self-contained: the story vocabulary lives IN this plugin (duplicated
// deliberately — plugins never import from each other). Deleting this file
// and its line in plugins/index.ts removes the Word Problems worksheet without
// affecting the framework or any other plugin.
//
// DEPTH DESIGN (quality over quantity): every item is a TWO-PART story whose
// parts (a)/(b) are connected — part (b) always continues the SAME scenario
// (the printed prompt carries "\n" line breaks; PrintableSheet's ProblemText
// is white-space: pre-wrap, so each part prints on its own line with its own
// "__" response blank). The six story families cover the reasoning strands a
// syllabus asks for at this age (V8/V9 problem-solving):
//   more-then-total  (two-step join, comparison language "more than")
//   two-gives        (two subtractions, part-part-whole of "given away")
//   compare-total    (difference AND sum of the same pair — related facts)
//   reverse-start    (working backwards from a result)
//   true-or-fix      (error analysis: judge a stated fact, then correct it)
//   estimate-first   (number sense: which ten is the sum closer to, then exact)
// The ANSWER string lists every part's result in order, comma-separated
// (RawProblem's documented multi-value convention) — so the answer key always
// contains the correct result for EVERY printed blank.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique, type Deck } from '../framework';

// Kid-friendly vocabulary for word problems (no money, no clock time — those
// are owned by the Money and Time sheets). Each pool is dealt from a deck so
// every name/thing appears before repeats. Singular forms pair index-aligned
// with the plurals so counts of 1 read grammatically ("Sam has 1 cookie").
const NAMES = ['Sam', 'Mia', 'Leo', 'Zoe', 'Tom', 'Max', 'Rae', 'Kai'] as const;
const THINGS = ['apples', 'toys', 'stickers', 'balloons', 'cookies', 'crayons', 'flowers', 'cars'] as const;
const THINGS_SING = ['apple', 'toy', 'sticker', 'balloon', 'cookie', 'crayon', 'flower', 'car'] as const;

// Grammatical count phrase: "1 cookie", "2 cookies".
const countOf = (n: number, idx: number) => `${n} ${n === 1 ? THINGS_SING[idx] : THINGS[idx]}`;
// Comparison count phrase: "1 more cookie", "2 more cookies".
const moreOf = (n: number, idx: number) => `${n} more ${n === 1 ? THINGS_SING[idx] : THINGS[idx]}`;

// k DISTINCT names from the deck. The deck holds 8 names, so at most a couple
// of redraws are ever needed; the final filter is a guaranteed-terminating
// fallback for the pathological cycle-boundary case (same as the previous
// generator's two-step redraw, generalised to k = 3).
const distinctNames = (deck: Deck<(typeof NAMES)[number]>, k: number): (typeof NAMES)[number][] => {
    const out: (typeof NAMES)[number][] = [];
    let guard = 0;
    while (out.length < k && guard < 20) {
        const n = deck.take();
        if (!out.includes(n)) out.push(n);
        guard += 1;
    }
    // Fallback (only reachable if the deck kept repeating): fill from the
    // static pool, deterministic and distinct.
    for (const n of NAMES) {
        if (out.length === k) break;
        if (!out.includes(n)) out.push(n);
    }
    return out;
};

// Word problems: two-part stories in familiar contexts, numbers from wordCap
// (Y1 within 20, Y2 within 30). EVERY constraint below keeps the WHOLE story —
// including intermediate part answers — inside the grade's number range, so no
// part ever asks a Year 1 student to work above within-20 (or Y2 above 30).
//
// NON-REPEATING SAMPLING: names and things are dealt from decks (even pool
// coverage) and the whole multi-part prompt passes through sampleUnique keyed
// on the printed text — the (form × names × things × numbers) cross-product
// keeps even a 100-page document repeat-free.
function generateWord(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(3, caps.wordCap);
    const nameDeck = createDeck(rng, NAMES);
    const thingDeck = createDeck(rng, THINGS.map((_, i) => i));
    return sampleUnique(
        count,
        () => {
            const idx = thingDeck.take();
            const thing = THINGS[idx];
            const form = rng.pick(['more', 'gives', 'compare', 'reverse', 'check', 'estimate'] as const);

            if (form === 'more') {
                // Two-step join: B has b MORE than A; (b) combines both.
                // a ≤ (cap-1)/2 guarantees 2a+b ≤ cap so both answers stay
                // within the grade's range.
                const a = rng.int(1, Math.max(1, Math.floor((cap - 1) / 2)));
                const b = rng.int(1, cap - 2 * a);
                const [n1, n2] = distinctNames(nameDeck, 2);
                return {
                    prompt:
                        `${n1} has ${countOf(a, idx)}. ${n2} has ${moreOf(b, idx)} than ${n1}.\n` +
                        `(a) How many ${thing} does ${n2} have? __\n` +
                        `(b) How many ${thing} do they have in total? __`,
                    answer: `${a + b}, ${2 * a + b}`
                };
            }
            if (form === 'gives') {
                // Two subtractions: (a) the total given away feeds (b) the
                // remainder. b + c ≤ a - 2 keeps a positive remainder.
                const a = rng.int(4, cap);
                const b = rng.int(1, a - 3);
                const c = rng.int(1, a - 1 - b);
                const [n1, n2, n3] = distinctNames(nameDeck, 3);
                return {
                    prompt:
                        `${n1} had ${countOf(a, idx)}. ${n1} gave ${countOf(b, idx)} to ${n2} and ${countOf(c, idx)} to ${n3}.\n` +
                        `(a) How many ${thing} did ${n1} give away? __\n` +
                        `(b) How many ${thing} does ${n1} have left? __`,
                    answer: `${b + c}, ${a - b - c}`
                };
            }
            if (form === 'compare') {
                // Related facts: the SAME pair answers the difference (a) and
                // the sum (b). Names print in sampled order so the prompt
                // never reveals which child has more.
                const a = rng.int(1, cap - 2);
                let b = rng.int(1, cap - a);
                if (b === a) b = a === 1 ? 2 : 1; // a tie would make (a) zero
                const [n1, n2] = distinctNames(nameDeck, 2);
                const [bigN, smallN] = a > b ? [n1, n2] : [n2, n1];
                return {
                    prompt:
                        `${n1} has ${countOf(a, idx)}. ${n2} has ${countOf(b, idx)}.\n` +
                        `(a) How many more ${thing} does ${bigN} have than ${smallN}? __\n` +
                        `(b) How many ${thing} do they have in total? __`,
                    answer: `${Math.abs(a - b)}, ${a + b}`
                };
            }
            if (form === 'reverse') {
                // Working backwards: the start is hidden; (b) continues
                // FORWARD from the recovered start. n+b+c ≤ cap by construction.
                const n = rng.int(1, cap - 2);
                const b = rng.int(1, cap - n - 1);
                const c = rng.int(1, cap - n - b);
                return {
                    prompt:
                        `Some ${thing} were in a box. ${b} of them were taken out. Now there are ${countOf(n, idx)}.\n` +
                        `(a) How many ${thing} were in the box at first? __\n` +
                        `(b) How many will there be after adding ${moreOf(c, idx)}? __`,
                    answer: `${n + b}, ${n + b + c}`
                };
            }
            if (form === 'check') {
                // Error analysis: judge a friend's statement (yes/no), then
                // state the correct result. Half the statements are correct so
                // the sheet is not a "always say no" pattern.
                const [n1] = distinctNames(nameDeck, 1);
                const isSum = rng.next() < 0.5;
                if (isSum) {
                    const a = rng.int(2, cap - 2);
                    const b = rng.int(1, cap - a);
                    const correct = a + b;
                    const ok = rng.next() < 0.5;
                    // A wrong statement is off by exactly 1 — close enough
                    // that the student must actually check. The cap branch
                    // keeps EVERY printed number (including the claim) inside
                    // the grade's range.
                    const stated = ok ? correct : correct < cap ? correct + (rng.next() < 0.5 ? 1 : -1) : correct - 1;
                    return {
                        prompt:
                            `${n1} says ${a} + ${b} = ${stated}.\n` +
                            `(a) Is ${n1} correct? __\n` +
                            `(b) What is the correct answer? __`,
                        answer: `${ok ? 'yes' : 'no'}, ${correct}`
                    };
                }
                const a = rng.int(3, cap);
                const b = rng.int(1, a - 1);
                const correct = a - b;
                const ok = rng.next() < 0.5;
                const stated = ok ? correct : correct < cap ? correct + (rng.next() < 0.5 ? 1 : -1) : correct - 1;
                return {
                    prompt:
                        `${n1} says ${a} - ${b} = ${stated}.\n` +
                        `(a) Is ${n1} correct? __\n` +
                        `(b) What is the correct answer? __`,
                    answer: `${ok ? 'yes' : 'no'}, ${correct}`
                };
            }
            // estimate: number sense BEFORE calculating — which ten is the sum
            // closer to, then the exact sum to check. s avoids multiples of 10
            // and midpoints (…5) so "closer to" is never ambiguous, and stays
            // above 10 so the lower candidate ten is at least 10.
            let s = rng.int(11, cap);
            if (s % 10 === 0 || s % 10 === 5) s -= 1;
            const lo = Math.floor(s / 10) * 10;
            const hi = lo + 10;
            const a = rng.int(2, s - 2);
            const b = s - a;
            const closer = s - lo < hi - s ? lo : hi;
            return {
                prompt:
                    `Do not work it out exactly yet: ${a} + ${b}.\n` +
                    `(a) Is the sum closer to ${lo} or ${hi}? __\n` +
                    `(b) What is the exact sum? __`,
                answer: `${closer}, ${s}`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const wordSpec: WorksheetSpec = {
    id: 'word',
    label: 'Word Problems',
    icon: '¶',
    // Four deep two-part stories per A4: prose rows need real working space
    // (the density reduction is the point — fewer, longer, connected tasks).
    perPage: 4,
    // Long prose questions read better one-per-row across the full page width.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('word'),
    scope: (grade: GradeConfig) => `two-part stories within ${Math.max(3, grade.caps.wordCap)}`,
    generate: generateWord
};

// The plugin: a function the dashboard calls with its framework bundle.
export function WordProblemsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(wordSpec);
}
