// ─────────────────────────────────────────────────────────────────────────────
// WORD PROBLEMS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `WordProblemsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Word Problems", glyph "¶") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). The sheet prints
//     in a single column (prose layout, singleColumn: true).
//
// Fully self-contained: the story vocabulary lives IN this plugin (duplicated
// deliberately — plugins never import from each other). Deleting this file
// and its line in plugins/index.ts removes the Word Problems worksheet without
// affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';

// Kid-friendly vocabulary for word problems (no money, no time, single-step).
const NAMES = ['Sam', 'Mia', 'Leo', 'Zoe', 'Tom', 'Max', 'Rae', 'Kai'] as const;
const THINGS = ['apples', 'toys', 'stickers', 'balloons', 'cookies', 'crayons', 'flowers', 'cars'] as const;

// Word problems: single-step add or subtract stories in familiar contexts.
// Numbers are drawn from wordCap. Addition keeps a + b <= wordCap.
function generateWord(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const out: RawProblem[] = [];
    const cap = Math.max(3, caps.wordCap);
    for (let i = 0; i < count; i++) {
        const thing = rng.pick(THINGS);
        if (rng.next() < 0.5) {
            // Addition story: two children combine their things.
            const a = rng.int(1, Math.max(1, cap - 2));
            const b = rng.int(1, cap - a); // b >= 1 and a+b <= cap
            const n1 = rng.pick(NAMES);
            let n2 = rng.pick(NAMES);
            if (n2 === n1) n2 = rng.pick(NAMES.filter((n) => n !== n1));
            out.push({
                prompt: `${n1} has ${a} ${thing}. ${n2} has ${b} ${thing}. How many ${thing} are there in total?`,
                answer: `${a + b}`
            });
        } else {
            // Subtraction story: a child gives some away. a >= 2, b in [1, a-1].
            const a = rng.int(2, cap);
            const b = rng.int(1, a - 1);
            const n1 = rng.pick(NAMES);
            out.push({
                prompt: `${n1} had ${a} ${thing}. ${n1} gave ${b} ${thing} to a friend. How many ${thing} does ${n1} have left?`,
                answer: `${a - b}`
            });
        }
    }
    return out;
}

// The plugin's declarative spec (exported for its own tests).
export const wordSpec: WorksheetSpec = {
    id: 'word',
    label: 'Word Problems',
    icon: '¶',
    perPage: 10,
    // Long prose questions read better one-per-row across the full page width.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('word'),
    scope: () => 'one-step',
    generate: generateWord
};

// The plugin: a function the dashboard calls with its framework bundle.
export function WordProblemsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(wordSpec);
}
