// ─────────────────────────────────────────────────────────────────────────────
// WORD PROBLEMS WORKSHEET — a self-contained dashboard plugin.
//
// The dashboard loads this plugin by calling `WordProblemsWorksheet(dashboard)`
// with its configurations + layouts (see plugins/index.ts). Within this
// function the plugin describes:
//   - its SIDEBAR LABEL ("Word Problems", glyph "¶") and which grades offer it;
//   - what happens when its label is CLICKED: its worksheet — generated by
//     the generator below — shows in the content area via the framework's
//     standard worksheet recipe (dashboard.createWorksheet). The sheet prints
//     in a single column (prose layout, singleColumn: true).
//
// Fully self-contained: the story vocabulary lives IN this plugin (duplicated
// deliberately — plugins never import from each other). Deleting this file
// and its line in plugins/index.ts removes the Word Problems worksheet without
// affecting the framework or any other plugin.
// ─────────────────────────────────────────────────────────────────────────────

import type { Caps, DashboardFramework, DashboardPlugin, GradeConfig, RawProblem, Rng, WorksheetSpec } from '../framework';
import { createDeck, sampleUnique } from '../framework';

// Kid-friendly vocabulary for word problems (no money, no time, single-step).
// Each pool is dealt from a deck so every name/thing appears before repeats.
// Singular forms pair index-aligned with the plurals so counts of 1 read
// grammatically ("Sam has 1 cookie", never "1 cookies").
const NAMES = ['Sam', 'Mia', 'Leo', 'Zoe', 'Tom', 'Max', 'Rae', 'Kai'] as const;
const THINGS = ['apples', 'toys', 'stickers', 'balloons', 'cookies', 'crayons', 'flowers', 'cars'] as const;
const THINGS_SING = ['apple', 'toy', 'sticker', 'balloon', 'cookie', 'crayon', 'flower', 'car'] as const;

// Grammatical count phrase: "1 cookie", "2 cookies".
const countOf = (n: number, idx: number) => `${n} ${n === 1 ? THINGS_SING[idx] : THINGS[idx]}`;

// Word problems: single-step add or subtract stories in familiar contexts.
// Numbers are drawn from wordCap. Addition keeps a + b <= wordCap.
//
// NON-REPEATING SAMPLING: names and things are dealt from decks (even pool
// coverage) and the whole question passes through sampleUnique keyed on the
// printed prompt — the same story with different children/things is a
// different question, and the (names x things x number pairs) cross-product
// keeps a 100-page document repeat-free.
function generateWord(rng: Rng, caps: Caps, count: number): RawProblem[] {
    const cap = Math.max(3, caps.wordCap);
    const nameDeck = createDeck(rng, NAMES);
    const thingDeck = createDeck(rng, THINGS.map((_, i) => i));
    return sampleUnique(
        count,
        () => {
            const idx = thingDeck.take();
            const thing = THINGS[idx];
            if (rng.next() < 0.5) {
                // Addition story: two children combine their things.
                const a = rng.int(1, Math.max(1, cap - 2));
                const b = rng.int(1, cap - a); // b >= 1 and a+b <= cap
                const n1 = nameDeck.take();
                // A second, different child (a deck of 8 names; the filter
                // redraw keeps the pair distinct even at cycle boundaries).
                let n2 = nameDeck.take();
                if (n2 === n1) n2 = nameDeck.take();
                if (n2 === n1) n2 = NAMES.find((n) => n !== n1)!;
                const total = a + b;
                return {
                    prompt: `${n1} has ${countOf(a, idx)}. ${n2} has ${countOf(b, idx)}. How many ${thing} are there in total?`,
                    answer: `${total}`
                };
            }
            // Subtraction story: a child gives some away. a >= 2, b in [1, a-1].
            const a = rng.int(2, cap);
            const b = rng.int(1, a - 1);
            const left = a - b;
            const n1 = nameDeck.take();
            return {
                prompt: `${n1} had ${countOf(a, idx)}. ${n1} gave ${countOf(b, idx)} to a friend. How many ${thing} does ${n1} have left?`,
                answer: `${left}`
            };
        },
        (p) => p.prompt
    );
}

// The plugin's declarative spec (exported for its own tests).
export const wordSpec: WorksheetSpec = {
    id: 'word',
    label: 'Word Problems',
    icon: '¶',
    perPage: 10,
    // Long prose questions read better one-per-row across the full page width.
    singleColumn: true,
    offered: (grade: GradeConfig) => grade.available.includes('word'),
    scope: () => 'one-step',
    generate: generateWord
};

// The plugin: a function the dashboard calls with its framework bundle.
export function WordProblemsWorksheet(dashboard: DashboardFramework): DashboardPlugin {
    return dashboard.createWorksheet(wordSpec);
}
